import { StyleSheet, Dimensions, Platform } from 'react-native';
import { MidnightColors, Fonts } from '../../constants/theme';
import { FunkyFonts } from './funkyFonts';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const baseStyles = {
headerGreeting: {
    color: MidnightColors.slate400,
    fontSize: 13,
    fontFamily: Fonts.inter.regular,
    marginTop: 4,
  },
  form: {
    gap: 16,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 11,
    color: '#cbd5e1',
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  safeArea: { flex: 1, backgroundColor: MidnightColors.background },
  centered: { justifyContent: 'center', alignItems: 'center' },
  container: { flex: 1 },

  // Hero
  hero: { height: 400, width: '100%' },
  heroImage: { ...StyleSheet.absoluteFillObject },
  goldenHeroImage: {
    transform: [{ scale: 1.02 }],
  },
  vintageHeroImage: {
    opacity: 0.42,
  },
  heroGradient: { ...StyleSheet.absoluteFillObject },
  floatingBack: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(2, 6, 23, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
  },
  popFloatingBack: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#0080ff',
    borderWidth: 3,
    borderColor: '#231f20',
    shadowColor: '#231f20',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  popFloatingShare: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#ff4fb8',
    borderWidth: 3,
    borderColor: '#231f20',
    shadowColor: '#231f20',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  popCustomNavbar: {
    position: 'absolute',
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 25,
  },
  vintageFloatingButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(21, 19, 15, 0.92)',
    borderColor: 'rgba(184, 145, 69, 0.72)',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    elevation: 4,
  },
  minimalFloatingButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#4a2f1d',
    borderColor: 'rgba(255, 250, 242, 0.36)',
    borderWidth: 1,
    shadowColor: '#6d4b34',
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 4,
  },
  floatingShare: { position: 'absolute', top: 20, right: 20, width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(0,0,0,0.4)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  heroContent: { position: 'absolute', bottom: 14, left: 24, right: 24 },
  heroTitle: { fontSize: 36, color: '#fff', fontFamily: Fonts.outfit.extraBold, letterSpacing: -1 },
  scrapbookHeroContent: {
    left: 18,
    right: 18,
    bottom: 12,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 253, 249, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(217, 130, 107, 0.22)',
  },
  scrapbookHeroRule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  scrapbookHeroRuleLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(38, 51, 49, 0.18)',
  },
  scrapbookHeroDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  scrapbookHeroTitle: {
    fontSize: 34,
    letterSpacing: 0,
    lineHeight: 38,
  },
  neonHeroContent: {
    left: 18,
    right: 18,
    bottom: 12,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 28,
    backgroundColor: 'rgba(9, 8, 24, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255, 61, 242, 0.42)',
    shadowColor: '#ff3df2',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.26,
    shadowRadius: 28,
    elevation: 8,
    overflow: 'hidden',
  },
  neonLightStreak: {
    position: 'absolute',
    height: 2,
    borderRadius: 999,
    opacity: 0.85,
  },
  neonLightStreakTop: {
    top: 16,
    right: -12,
    width: 132,
    backgroundColor: '#66e8ff',
    transform: [{ rotate: '-12deg' }],
  },
  neonLightStreakBottom: {
    left: -18,
    bottom: 18,
    width: 110,
    backgroundColor: '#ff3df2',
    transform: [{ rotate: '-10deg' }],
  },
  neonHeroChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(102, 232, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(102, 232, 255, 0.34)',
    marginBottom: 12,
  },
  neonHeroChipDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#66e8ff',
  },
  neonHeroChipText: {
    color: '#e9fbff',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  neonHeroDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  neonHeroDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(102, 232, 255, 0.24)',
  },
  neonHeroDividerCore: {
    width: 42,
    height: 3,
    borderRadius: 999,
    backgroundColor: '#ff3df2',
  },
  neonHeroTitle: {
    fontSize: 38,
    lineHeight: 42,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  neonHeroMeta: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  neonHeroDate: {
    color: '#66e8ff',
    letterSpacing: 1.2,
  },
  neonShareButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 61, 242, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255, 61, 242, 0.36)',
  },
  pastelHeroContent: {
    left: 18,
    right: 18,
    bottom: 12,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 253, 251, 0.76)',
    borderWidth: 1,
    borderColor: 'rgba(213, 180, 220, 0.34)',
    shadowColor: '#d8b4dc',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.2,
    shadowRadius: 26,
    elevation: 6,
    overflow: 'hidden',
  },
  pastelFloatOrb: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.42,
  },
  pastelFloatOrbPink: {
    width: 92,
    height: 92,
    right: -28,
    top: -22,
    backgroundColor: '#f8c8d8',
  },
  pastelFloatOrbBlue: {
    width: 70,
    height: 70,
    left: -22,
    bottom: -20,
    backgroundColor: '#cdeaf6',
  },
  pastelHeroChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 241, 232, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(201, 118, 139, 0.18)',
    marginBottom: 12,
  },
  pastelHeroSparkle: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#d8b4dc',
  },
  pastelHeroChipText: {
    color: '#8b6f70',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  pastelHeroDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  pastelHeroDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(154, 133, 131, 0.22)',
  },
  pastelHeroDividerDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#f4b8a8',
  },
  pastelHeroDividerDotAlt: {
    backgroundColor: '#bddfd9',
  },
  pastelHeroTitle: {
    fontSize: 36,
    lineHeight: 41,
    letterSpacing: 0,
  },
  pastelHeroMeta: {
    alignSelf: 'flex-start',
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.58)',
    borderWidth: 1,
    borderColor: 'rgba(201, 118, 139, 0.16)',
  },
  pastelHeroDate: {
    color: '#c9768b',
    letterSpacing: 0.9,
  },
  pastelShareButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(216, 180, 220, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(201, 118, 139, 0.2)',
  },
  anniversaryRibbon: {
    position: 'absolute',
    height: 3,
    left: 20,
    right: 20,
    top: 18,
    borderRadius: 999,
  },
  goldenRibbon: {
    backgroundColor: 'rgba(201, 154, 46, 0.72)',
  },
  goldenHeroContent: {
    left: 18,
    right: 18,
    bottom: 24,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 250, 240, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(201, 154, 46, 0.34)',
    shadowColor: '#c99a2e',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.2,
    shadowRadius: 26,
    elevation: 5,
  },
  goldenHeroLabel: {
    color: '#8a6421',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.6,
    marginBottom: 12,
  },
  goldenHeroRule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  goldenHeroRuleLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(201, 154, 46, 0.38)',
  },
  goldenHeroMedallion: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#c99a2e',
    backgroundColor: '#fff7e6',
  },
  goldenHeroTitle: {
    fontSize: 39,
    lineHeight: 42,
    fontFamily: Fonts.cormorant.bold,
    color: '#3f2f22',
    letterSpacing: 0,
  },
  goldenHeroMeta: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(201, 154, 46, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(201, 154, 46, 0.26)',
  },
  vintageHeroContent: {
    left: 20,
    right: 20,
    bottom: 28,
    paddingHorizontal: 22,
    paddingVertical: 22,
    borderRadius: 2,
    backgroundColor: 'rgba(245, 239, 228, 0.9)',
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.14,
    shadowRadius: 26,
    elevation: 4,
  },
  vintageHeroIssue: {
    color: '#5e5348',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2.2,
    marginBottom: 12,
  },
  vintageHeroRule: {
    height: 1,
    backgroundColor: 'rgba(23, 23, 23, 0.16)',
    marginBottom: 14,
  },
  vintageHeroTitle: {
    fontSize: 40,
    lineHeight: 42,
    fontFamily: Fonts.cormorant.bold,
    letterSpacing: 0.25,
    textTransform: 'uppercase',
  },
  vintageHeroMeta: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 0,
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(23, 23, 23, 0.46)',
    backgroundColor: 'rgba(23, 23, 23, 0.045)',
  },
  roseHeroContent: {
    left: 18,
    right: 18,
    bottom: 24,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 252, 247, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.18)',
    shadowColor: '#b76578',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.16,
    shadowRadius: 26,
    elevation: 4,
    overflow: 'hidden',
  },
  rosePetal: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: 'rgba(199, 95, 114, 0.16)',
  },
  rosePetalOne: {
    width: 92,
    height: 92,
    right: -28,
    top: -28,
  },
  rosePetalTwo: {
    width: 64,
    height: 64,
    left: -20,
    bottom: -18,
    backgroundColor: 'rgba(237, 178, 187, 0.2)',
  },
  roseHeroLabel: {
    color: '#9a6c74',
    fontSize: 10,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 10,
  },
  roseHeroVine: {
    width: 88,
    height: 1,
    borderRadius: 999,
    backgroundColor: '#b76578',
    marginBottom: 12,
  },
  roseHeroTitle: {
    fontSize: 38,
    lineHeight: 42,
    fontFamily: Fonts.cormorant.bold,
    color: '#562733',
    letterSpacing: 0,
  },
  roseHeroMeta: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(183, 101, 120, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.2)',
  },
  minimalHeroContent: {
    left: 20,
    right: 20,
    bottom: 26,
    paddingHorizontal: 22,
    paddingVertical: 22,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 250, 242, 0.9)',
    borderWidth: 1,
    borderColor: 'rgba(109, 75, 52, 0.1)',
  },
  minimalHeroLabel: {
    color: '#8a7461',
    fontSize: 10,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.8,
    marginBottom: 10,
  },
  minimalHeroRule: {
    width: 48,
    height: 1,
    backgroundColor: '#6d4b34',
    marginBottom: 12,
  },
  minimalHeroTitle: {
    color: '#3b2618',
    fontSize: 38,
    lineHeight: 40,
    fontFamily: Fonts.cormorant.bold,
    letterSpacing: 0,
  },
  minimalHeroMeta: {
    alignSelf: 'flex-start',
    paddingHorizontal: 0,
    paddingVertical: 6,
    borderRadius: 0,
    backgroundColor: 'transparent',
  },
  anniversaryHeroDate: {
    letterSpacing: 1,
  },
  anniversaryShareButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  goldenCeremonyHero: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingBottom: 40,
    overflow: 'hidden',
  },
  goldenCeremonyVignette: {
    ...StyleSheet.absoluteFillObject,
  },
  goldenCeremonyCreamWash: {
    ...StyleSheet.absoluteFillObject,
  },
  goldenCeremonyTexture: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.42,
  },
  goldenGrainLine: {
    position: 'absolute',
    height: 1,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 250, 240, 0.2)',
  },
  goldenGrainLineOne: {
    left: 30,
    right: 54,
    top: 182,
  },
  goldenGrainLineTwo: {
    left: 76,
    right: 26,
    bottom: 218,
    backgroundColor: 'rgba(201, 154, 46, 0.1)',
  },
  goldenGrainDot: {
    position: 'absolute',
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 250, 240, 0.26)',
  },
  goldenGrainDotOne: {
    left: 52,
    top: 140,
  },
  goldenGrainDotTwo: {
    right: 82,
    top: 272,
  },
  goldenGrainDotThree: {
    left: 112,
    bottom: 168,
    backgroundColor: 'rgba(201, 154, 46, 0.16)',
  },
  goldenCeremonyHalo: {
    position: 'absolute',
    top: 70,
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: 'rgba(201, 154, 46, 0.14)',
    transform: [{ scaleX: 1.42 }],
  },
  goldenCeremonyFrame: {
    position: 'absolute',
    top: 94,
    left: 22,
    right: 22,
    bottom: 32,
    borderWidth: 1,
    borderColor: 'rgba(255, 247, 230, 0.32)',
    borderRadius: 36,
  },
  goldenCeremonyCorner: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderColor: 'rgba(201, 154, 46, 0.38)',
  },
  goldenCeremonyCornerTopLeft: {
    top: 12,
    left: 12,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderTopLeftRadius: 16,
  },
  goldenCeremonyCornerTopRight: {
    top: 12,
    right: 12,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderTopRightRadius: 16,
  },
  goldenCeremonyCornerBottomLeft: {
    bottom: 12,
    left: 12,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderBottomLeftRadius: 16,
  },
  goldenCeremonyCornerBottomRight: {
    bottom: 12,
    right: 12,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderBottomRightRadius: 16,
  },
  goldenCeremonyPhotoMotion: {
    position: 'absolute',
    top: 122,
    right: 30,
    width: 138,
    height: 178,
  },
  goldenCeremonyPhotoCard: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: 'rgba(255, 250, 240, 0.82)',
    transform: [{ rotate: '2deg' }],
    shadowColor: '#3f2f22',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.16,
    shadowRadius: 28,
    elevation: 5,
  },
  goldenCeremonyPhoto: {
    width: '100%',
    height: '100%',
  },
  goldenCeremonyPhotoVeil: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(201, 154, 46, 0.1)',
  },
  goldenCeremonyYearRail: {
    position: 'absolute',
    left: 26,
    top: 136,
    paddingVertical: 12,
    paddingHorizontal: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 250, 240, 0.58)',
    borderWidth: 0,
  },
  goldenCeremonyYearRailText: {
    color: '#8a6421',
    fontSize: 9,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2.3,
    writingDirection: 'ltr',
    transform: [{ rotate: '-90deg' }],
  },
  goldenCeremonyContent: {
    width: '92%',
    alignItems: 'center',
    paddingHorizontal: 26,
    paddingTop: 36,
    paddingBottom: 26,
    borderTopLeftRadius: 48,
    borderTopRightRadius: 48,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    backgroundColor: 'rgba(255, 250, 240, 0.86)',
    borderWidth: 0,
    shadowColor: '#c99a2e',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.18,
    shadowRadius: 38,
    elevation: 6,
  },
  goldenCeremonyKicker: {
    color: '#9a6f22',
    fontSize: 10.5,
    fontFamily: Fonts.nunitoSans.semiBold,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    marginBottom: 13,
  },
  goldenCeremonySeal: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#c99a2e',
    borderWidth: 2,
    borderColor: 'rgba(255, 247, 230, 0.86)',
    marginBottom: 18,
  },
  goldenCeremonySealText: {
    color: '#fff7e6',
    fontSize: 24,
    fontFamily: Fonts.cormorant.bold,
  },
  goldenCeremonyTitle: {
    color: '#3f2f22',
    fontSize: 40,
    lineHeight: 45,
    fontFamily: Fonts.cormorant.semiBold,
    textAlign: 'center',
    letterSpacing: 0,
    marginHorizontal: 4,
  },
  goldenCeremonyRule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    width: '82%',
    marginTop: 18,
    marginBottom: 13,
  },
  goldenCeremonyRuleLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(201, 154, 46, 0.32)',
  },
  goldenCeremonyRuleDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(201, 154, 46, 0.78)',
  },
  goldenCeremonyDate: {
    color: '#81633f',
    fontSize: 12,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.55,
  },
  goldenCeremonyShare: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 20,
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: 'rgba(201, 154, 46, 0.18)',
    borderWidth: 0,
  },
  goldenCeremonyShareText: {
    color: '#3f2f22',
    fontSize: 11,
    fontFamily: Fonts.nunitoSans.bold,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  vintageEditorialHero: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    paddingTop: 76,
    paddingBottom: 30,
    paddingHorizontal: 22,
    overflow: 'hidden',
    backgroundColor: '#0F0E0B',
  },
  vintageEditorialVignette: {
    ...StyleSheet.absoluteFillObject,
  },
  vintageEditorialTexture: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.34,
  },
  vintageGrainLine: {
    position: 'absolute',
    height: 1,
    backgroundColor: 'rgba(184, 145, 69, 0.18)',
  },
  vintageGrainLineOne: {
    left: 24,
    right: 40,
    top: 132,
  },
  vintageGrainLineTwo: {
    left: 58,
    right: 22,
    bottom: 88,
    backgroundColor: 'rgba(239, 227, 199, 0.08)',
  },
  vintageGrainDot: {
    position: 'absolute',
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(184, 145, 69, 0.22)',
  },
  vintageGrainDotOne: {
    left: 46,
    top: 188,
  },
  vintageGrainDotTwo: {
    right: 54,
    top: 256,
  },
  vintageGrainDotThree: {
    left: 132,
    bottom: 132,
    backgroundColor: 'rgba(239, 227, 199, 0.13)',
  },
  vintageEditorialMasthead: {
    alignItems: 'center',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(184, 145, 69, 0.46)',
    backgroundColor: 'rgba(15, 14, 11, 0.78)',
  },
  vintageEditorialMastheadText: {
    color: '#F2E7D2',
    fontSize: 12,
    fontFamily: Fonts.cormorant.bold,
    textTransform: 'uppercase',
    letterSpacing: 2.6,
  },
  vintageEditorialTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(184, 145, 69, 0.34)',
    paddingVertical: 10,
  },
  vintageEditorialFeatureRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 13,
  },
  vintageEditorialImagePlate: {
    flex: 1,
    height: 148,
    padding: 8,
    backgroundColor: '#D6C29A',
    borderWidth: 1,
    borderColor: 'rgba(184, 145, 69, 0.62)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.34,
    shadowRadius: 28,
    elevation: 4,
  },
  vintageEditorialTape: {
    position: 'absolute',
    top: -8,
    left: 28,
    width: 54,
    height: 17,
    backgroundColor: 'rgba(232, 216, 184, 0.58)',
    borderWidth: 1,
    borderColor: 'rgba(184, 145, 69, 0.24)',
    transform: [{ rotate: '-3deg' }],
    zIndex: 4,
  },
  vintageEditorialClip: {
    position: 'absolute',
    top: 12,
    right: 18,
    width: 13,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(33, 26, 18, 0.45)',
    backgroundColor: 'rgba(239, 227, 199, 0.26)',
    zIndex: 4,
  },
  vintageEditorialImage: {
    width: '100%',
    height: '100%',
    opacity: 0.86,
  },
  vintageEditorialImageFade: {
    ...StyleSheet.absoluteFillObject,
    margin: 8,
  },
  vintageEditorialNumberBlock: {
    width: 84,
    height: 148,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2A241B',
    borderWidth: 1,
    borderColor: 'rgba(184, 145, 69, 0.52)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.28,
    shadowRadius: 22,
    elevation: 3,
  },
  vintageEditorialNumber: {
    color: '#B89145',
    fontSize: 50,
    lineHeight: 52,
    fontFamily: Fonts.cormorant.bold,
  },
  vintageEditorialNumberLabel: {
    color: '#F2E7D2',
    fontSize: 9,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.9,
  },
  vintageEditorialEdition: {
    color: '#C7A96B',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.7,
  },
  vintageEditorialBand: {
    alignSelf: 'stretch',
    backgroundColor: '#E8D8B8',
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: 'rgba(184, 145, 69, 0.6)',
    borderLeftWidth: 3,
    borderLeftColor: '#B89145',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 4,
  },
  vintageEditorialTitle: {
    color: '#211A12',
    fontSize: 43,
    lineHeight: 43,
    fontFamily: Fonts.cormorant.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  vintageEditorialFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  vintageEditorialDate: {
    color: '#C7A96B',
    fontSize: 12,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.6,
  },
  vintageEditorialShare: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#15130F',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(184, 145, 69, 0.62)',
  },
  vintageEditorialShareText: {
    color: '#B89145',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.25,
  },
  roseBloomHero: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    paddingHorizontal: 22,
    paddingBottom: 30,
    overflow: 'hidden',
    backgroundColor: '#fff9f5',
  },
  roseBloomWash: {
    ...StyleSheet.absoluteFillObject,
  },
  roseBloomGrain: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.42,
  },
  roseBloomGrainDot: {
    position: 'absolute',
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(154, 108, 116, 0.16)',
  },
  roseBloomGrainDotOne: {
    top: 112,
    left: 62,
  },
  roseBloomGrainDotTwo: {
    top: 238,
    right: 46,
    backgroundColor: 'rgba(143, 159, 123, 0.16)',
  },
  roseBloomGrainDotThree: {
    bottom: 118,
    left: 118,
  },
  roseBloomHeader: {
    position: 'absolute',
    top: 78,
    left: 24,
    right: 24,
    alignItems: 'center',
    zIndex: 3,
  },
  roseBloomHeaderTitle: {
    color: '#562733',
    fontSize: 14,
    lineHeight: 18,
    fontFamily: Fonts.cormorant.bold,
    textTransform: 'uppercase',
    letterSpacing: 2.2,
  },
  roseBloomHeaderSubtitle: {
    color: '#8b5962',
    fontSize: 12,
    lineHeight: 17,
    fontFamily: Fonts.nunitoSans.semiBold,
    letterSpacing: 0.5,
    marginTop: 3,
  },
  roseBloomHeaderDivider: {
    marginTop: 10,
    width: '58%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  roseBloomHeaderLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(183, 101, 120, 0.28)',
  },
  roseBloomHeaderFlower: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  roseBloomHeaderPetal: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 5,
    backgroundColor: 'rgba(183, 101, 120, 0.34)',
  },
  roseBloomHeaderPetalTop: {
    top: 1,
  },
  roseBloomHeaderPetalRight: {
    right: 1,
    backgroundColor: 'rgba(143, 159, 123, 0.24)',
  },
  roseBloomHeaderPetalBottom: {
    bottom: 1,
  },
  roseBloomHeaderPetalLeft: {
    left: 1,
    backgroundColor: 'rgba(143, 159, 123, 0.24)',
  },
  roseBloomOrb: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: 'rgba(248, 218, 224, 0.48)',
  },
  roseBloomOrbLarge: {
    width: 300,
    height: 300,
    right: -105,
    top: 58,
  },
  roseBloomOrbSmall: {
    width: 118,
    height: 118,
    left: -34,
    bottom: 92,
    backgroundColor: 'rgba(183, 101, 120, 0.16)',
  },
  roseBloomVine: {
    position: 'absolute',
    top: 112,
    left: 22,
    width: 86,
    height: 230,
    borderLeftWidth: 1,
    borderColor: 'rgba(143, 159, 123, 0.34)',
    borderTopLeftRadius: 80,
  },
  roseBloomPetal: {
    position: 'absolute',
    width: 42,
    height: 26,
    borderTopLeftRadius: 24,
    borderBottomRightRadius: 24,
    backgroundColor: 'rgba(255, 252, 247, 0.72)',
  },
  roseBloomPetalA: {
    top: 20,
    left: 16,
    transform: [{ rotate: '-18deg' }],
  },
  roseBloomPetalB: {
    top: 96,
    left: -8,
    backgroundColor: 'rgba(215, 155, 166, 0.38)',
    transform: [{ rotate: '18deg' }],
  },
  roseBloomPetalC: {
    top: 160,
    left: 20,
    transform: [{ rotate: '-8deg' }],
  },
  roseBloomPhotoStamp: {
    position: 'absolute',
    top: 150,
    right: 24,
    width: 142,
    height: 172,
    padding: 7,
    borderRadius: 26,
    backgroundColor: 'rgba(255, 252, 247, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.14)',
    transform: [{ rotate: '4deg' }],
    shadowColor: '#b76578',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 7,
  },
  roseBloomPhotoTape: {
    position: 'absolute',
    top: -8,
    left: 28,
    width: 56,
    height: 18,
    borderRadius: 7,
    backgroundColor: 'rgba(255, 235, 225, 0.66)',
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.12)',
    transform: [{ rotate: '-5deg' }],
    zIndex: 5,
  },
  roseBloomPhotoCorner: {
    position: 'absolute',
    right: 13,
    bottom: 13,
    width: 28,
    height: 28,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(143, 159, 123, 0.38)',
    borderBottomRightRadius: 10,
    zIndex: 5,
  },
  roseBloomPhoto: {
    width: '100%',
    height: '100%',
    borderRadius: 19,
    opacity: 0.92,
  },
  roseBloomMomentCard: {
    position: 'absolute',
    top: 212,
    left: 26,
    width: 94,
    minHeight: 102,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 252, 247, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.2)',
    shadowColor: '#b76578',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.13,
    shadowRadius: 22,
    elevation: 5,
    alignItems: 'center',
  },
  roseBloomMomentNumber: {
    color: '#562733',
    fontSize: 42,
    lineHeight: 43,
    fontFamily: Fonts.cormorant.bold,
  },
  roseBloomMomentLabel: {
    color: '#9a6c74',
    fontSize: 9.5,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    marginTop: 2,
  },
  roseBloomMomentDivider: {
    width: 34,
    height: 1,
    backgroundColor: 'rgba(143, 159, 123, 0.42)',
    marginTop: 9,
  },
  roseBloomCard: {
    width: '100%',
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 24,
    borderTopLeftRadius: 46,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 42,
    backgroundColor: 'rgba(255, 252, 247, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.2)',
    shadowColor: '#b76578',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.14,
    shadowRadius: 30,
    elevation: 7,
  },
  roseBloomKickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginBottom: 12,
  },
  roseBloomKickerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#8f9f7b',
  },
  roseBloomKickerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(183, 101, 120, 0.22)',
  },
  roseBloomKicker: {
    color: '#9a6c74',
    fontSize: 10.5,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.8,
  },
  roseBloomTitle: {
    color: '#562733',
    fontSize: 42,
    lineHeight: 44,
    fontFamily: Fonts.cormorant.bold,
    letterSpacing: 0,
  },
  roseBloomStem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 16,
    marginBottom: 12,
  },
  roseBloomStemLine: {
    width: 86,
    height: 1,
    borderRadius: 999,
    backgroundColor: 'rgba(183, 101, 120, 0.56)',
  },
  roseBloomLeaf: {
    width: 10,
    height: 10,
    borderRadius: 6,
    backgroundColor: '#8f9f7b',
  },
  roseBloomLeafAlt: {
    backgroundColor: '#d79ba6',
  },
  roseBloomDate: {
    color: '#8b5962',
    fontSize: 12,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.35,
  },
  roseBloomShare: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 18,
    paddingHorizontal: 19,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: 'rgba(183, 101, 120, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.24)',
  },
  roseBloomShareText: {
    color: '#562733',
    fontSize: 11,
    fontFamily: Fonts.nunitoSans.bold,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  minimalEditorialHero: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    paddingHorizontal: 24,
    paddingBottom: 28,
    overflow: 'hidden',
    backgroundColor: '#f7efe4',
  },
  minimalEditorialWash: {
    ...StyleSheet.absoluteFillObject,
  },
  minimalEditorialBotanical: {
    position: 'absolute',
    width: 92,
    height: 118,
    opacity: 0.28,
  },
  minimalEditorialBotanicalLeft: {
    left: -20,
    bottom: 72,
    transform: [{ rotate: '-18deg' }],
  },
  minimalEditorialBotanicalRight: {
    right: -18,
    top: 126,
    transform: [{ rotate: '164deg' }],
  },
  minimalEditorialStem: {
    position: 'absolute',
    left: 44,
    top: 8,
    width: 1,
    height: 104,
    backgroundColor: 'rgba(109, 75, 52, 0.34)',
  },
  minimalEditorialLeaf: {
    position: 'absolute',
    width: 30,
    height: 15,
    borderTopLeftRadius: 30,
    borderBottomRightRadius: 30,
    backgroundColor: 'rgba(178, 151, 119, 0.42)',
  },
  minimalEditorialLeafOne: {
    top: 30,
    left: 45,
    transform: [{ rotate: '22deg' }],
  },
  minimalEditorialLeafTwo: {
    top: 66,
    left: 15,
    transform: [{ rotate: '-28deg' }],
  },
  minimalEditorialPhotoPanel: {
    position: 'absolute',
    top: 92,
    right: 22,
    width: 166,
    height: 198,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#fffaf2',
    padding: 9,
    paddingBottom: 22,
    shadowColor: '#6d4b34',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 28,
    elevation: 5,
    transform: [{ rotate: '2deg' }],
  },
  minimalEditorialTape: {
    position: 'absolute',
    top: -5,
    left: 48,
    width: 68,
    height: 20,
    borderRadius: 5,
    backgroundColor: 'rgba(214, 190, 156, 0.55)',
    borderWidth: 1,
    borderColor: 'rgba(109, 75, 52, 0.08)',
    zIndex: 3,
    transform: [{ rotate: '-5deg' }],
  },
  minimalEditorialPhoto: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  minimalEditorialPhotoFade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(109, 75, 52, 0.04)',
  },
  minimalEditorialGridLineVertical: {
    position: 'absolute',
    top: 82,
    bottom: 42,
    left: 56,
    width: 1,
    backgroundColor: 'rgba(109, 75, 52, 0.08)',
  },
  minimalEditorialGridLineHorizontal: {
    position: 'absolute',
    top: 304,
    left: 24,
    right: 24,
    height: 1,
    backgroundColor: 'rgba(109, 75, 52, 0.08)',
  },
  minimalEditorialContent: {
    width: '86%',
    paddingHorizontal: 22,
    paddingVertical: 24,
    borderRadius: 26,
    backgroundColor: 'rgba(255, 250, 242, 0.91)',
    borderWidth: 1,
    borderColor: 'rgba(109, 75, 52, 0.1)',
    shadowColor: '#6d4b34',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 4,
  },
  minimalEditorialKicker: {
    color: '#8a7461',
    fontSize: 10.5,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2.1,
    marginBottom: 12,
  },
  minimalEditorialTitle: {
    color: '#3b2618',
    fontSize: 43,
    lineHeight: 45,
    fontFamily: Fonts.cormorant.bold,
    letterSpacing: 0,
  },
  minimalEditorialDivider: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  minimalEditorialDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(109, 75, 52, 0.18)',
  },
  minimalEditorialDividerOrnament: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#6d4b34',
  },
  minimalEditorialMetaRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  minimalEditorialDate: {
    color: '#6d4b34',
    fontSize: 12,
    fontFamily: Fonts.nunitoSans.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  minimalEditorialShare: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4a2f1d',
    shadowColor: '#6d4b34',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 14,
    elevation: 3,
  },
  minimalEditorialIndex: {
    position: 'absolute',
    top: 96,
    left: 24,
    width: 70,
    height: 82,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 250, 242, 0.26)',
    backgroundColor: '#4a2f1d',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#6d4b34',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 22,
    elevation: 3,
  },
  minimalEditorialIndexText: {
    color: '#fffaf2',
    fontSize: 27,
    lineHeight: 29,
    fontFamily: Fonts.cormorant.bold,
  },
  minimalEditorialIndexLabel: {
    marginTop: 1,
    color: '#d6be9c',
    fontSize: 8.5,
    fontFamily: Fonts.nunitoSans.bold,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  popHeroContent: {
    left: 18,
    right: 18,
    bottom: 12,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 24,
    backgroundColor: '#fffdf3',
    borderWidth: 3,
    borderColor: '#231f20',
    shadowColor: '#0080ff',
    shadowOffset: { width: 8, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    overflow: 'hidden',
  },
  popBurstShape: {
    position: 'absolute',
    width: 82,
    height: 82,
    borderRadius: 18,
    borderWidth: 3,
    borderColor: '#231f20',
    opacity: 0.92,
  },
  popBurstShapePink: {
    right: -28,
    top: -24,
    backgroundColor: '#ff4fb8',
    transform: [{ rotate: '18deg' }],
  },
  popBurstShapeBlue: {
    left: -34,
    bottom: -30,
    backgroundColor: '#0080ff',
    transform: [{ rotate: '-16deg' }],
  },
  popHeroSticker: {
    position: 'absolute',
    right: 18,
    top: 18,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#ffe84a',
    borderWidth: 3,
    borderColor: '#231f20',
    transform: [{ rotate: '8deg' }],
    zIndex: 2,
  },
  popHeroStickerText: {
    color: '#231f20',
    fontSize: 13,
    fontFamily: FunkyFonts.marker,
    letterSpacing: 0,
  },
  popHeroChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: '#ff4fb8',
    borderWidth: 3,
    borderColor: '#231f20',
    marginBottom: 12,
  },
  popHeroChipDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffe84a',
    borderWidth: 1,
    borderColor: '#231f20',
  },
  popHeroChipText: {
    color: '#231f20',
    fontSize: 20,
    fontFamily: FunkyFonts.marker,
    textTransform: 'uppercase',
    letterSpacing: -0.2,
    marginBottom: 10,
    marginTop: 6,
    alignSelf: 'center',
  },
  popHeroDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  popHeroDividerLine: {
    flex: 1,
    height: 3,
    backgroundColor: '#231f20',
  },
  popHeroDividerBlock: {
    width: 22,
    height: 12,
    backgroundColor: '#0080ff',
    borderWidth: 2,
    borderColor: '#231f20',
    transform: [{ rotate: '-8deg' }],
  },
  popHeroDividerBlockAlt: {
    backgroundColor: '#ef2b3a',
    transform: [{ rotate: '8deg' }],
  },
  popHeroTitle: {
    fontSize: 40,
    lineHeight: 44,
    letterSpacing: 0,
    textTransform: 'uppercase',
    fontFamily: FunkyFonts.marker,
  },
  popHeroMeta: {
    alignSelf: 'flex-start',
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: '#ffe84a',
    borderWidth: 3,
    borderColor: '#231f20',
  },
  popHeroDate: {
    color: '#231f20',
    letterSpacing: 0.5,
    fontFamily: FunkyFonts.marker,
    fontSize: 14,
  },
  popShareButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 16,
    backgroundColor: '#0080ff',
    borderWidth: 3,
    borderColor: '#231f20',
  },

  // Content
  content: { padding: 24 },
  description: { fontSize: 16, color: MidnightColors.slate400, fontFamily: Fonts.inter.regular, lineHeight: 24, marginBottom: 32 },

  // Tabs
  tabBar: { flexDirection: 'row', gap: 12, marginBottom: 24, backgroundColor: 'rgba(255,255,255,0.05)', padding: 6, borderRadius: 16 },
  tab: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 12 },
  activeTab: { backgroundColor: MidnightColors.gold },
  tabText: { color: MidnightColors.slate400, fontSize: 13, fontFamily: Fonts.outfit.bold },
  activeTabText: { color: MidnightColors.background },
  badge: { position: 'absolute', top: 4, right: 4, minWidth: 16, height: 16, borderRadius: 8, backgroundColor: '#ef4444', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, borderWidth: 1, borderColor: MidnightColors.background },
  badgeText: { color: '#fff', fontSize: 9, fontFamily: Fonts.inter.bold },

  // Section
  section: { marginBottom: 32 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  sectionTitle: { fontSize: 22, color: '#fff', fontFamily: Fonts.outfit.bold },
  addBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(212,175,55,0.12)', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(212,175,55,0.25)' },
  addBtnText: { color: MidnightColors.gold, fontSize: 12, fontFamily: Fonts.outfit.bold },

  subGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  subCard: { width: (SCREEN_WIDTH - 60) / 2, height: 185, borderRadius: 16, overflow: 'hidden', backgroundColor: MidnightColors.deepSlate, borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.08)' },
  subImage: { width: '100%', height: 110 },
  subImageFull: { position: 'absolute', width: '100%', height: '100%', resizeMode: 'cover' },
  subInfo: { padding: 10 },
  subInfoOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 12, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 8 },
  subTitle: { fontSize: 14, color: '#fff', fontFamily: Fonts.outfit.bold },
  subTitleOverlay: { fontSize: 13, color: '#ffffff', fontFamily: Fonts.outfit.bold, flex: 1, lineHeight: 17, textShadowColor: 'rgba(0, 0, 0, 0.5)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 3 },
  subArrowCircle: { width: 20, height: 20, borderRadius: 10, backgroundColor: 'rgba(255, 255, 255, 0.2)', alignItems: 'center', justifyContent: 'center', borderWidth: 0.5, borderColor: 'rgba(255, 255, 255, 0.3)' },
  badgeContainer: { position: 'absolute', top: 10, left: 10, zIndex: 10 },
  badgeGradient: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  badgeTextLabel: { color: '#000000', fontSize: 8, fontFamily: Fonts.inter.bold, letterSpacing: 0.5 },
  subBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(0, 0, 0, 0.65)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, borderWidth: 0.5, borderColor: 'rgba(255, 255, 255, 0.2)' },
  subBadgeTextLabel: { color: 'rgba(255, 255, 255, 0.95)', fontSize: 8, fontFamily: Fonts.inter.bold, letterSpacing: 0.5 },

  // Logs
  logCard: { backgroundColor: 'rgba(255,255,255,0.03)', padding: 16, borderRadius: 16, borderLeftWidth: 3, borderLeftColor: MidnightColors.gold, marginBottom: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  logName: { color: '#fff', fontSize: 16, fontFamily: Fonts.outfit.bold },
  logPhone: { color: MidnightColors.slate400, fontSize: 12, fontFamily: Fonts.inter.medium, marginTop: 2 },
  logActions: { flexDirection: 'row', gap: 10 },
  statusBtn: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  statusText: { fontSize: 10, fontFamily: Fonts.inter.bold, letterSpacing: 1 },
  deleteLogBtn: { padding: 8 },
  emptyContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40, gap: 12 },
  emptyText: { color: MidnightColors.slate400, fontSize: 14, fontFamily: Fonts.inter.regular, fontStyle: 'italic', textAlign: 'center' },
  manageApprovedToggle: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, backgroundColor: 'rgba(255,255,255,0.02)', borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  manageApprovedText: { color: '#64748b', fontSize: 13, fontFamily: Fonts.inter.bold },

  // Member Card
  memberCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 24,
    paddingHorizontal: 16,
    height: 84,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    gap: 16
  },
  memberAvatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: 'rgba(212, 175, 55, 0.1)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(212, 175, 55, 0.2)' },
  avatarText: { color: MidnightColors.gold, fontSize: 20, fontFamily: Fonts.outfit.bold },
  memberMain: { flex: 1, height: '100%', justifyContent: 'center', paddingBottom: 12 },
  memberName: { color: '#fff', fontSize: 17, fontFamily: Fonts.outfit.bold, lineHeight: 22 },
  memberSecondary: { position: 'absolute', bottom: 4, left: 0, right: 0, flexDirection: 'row', alignItems: 'center', gap: 8 },
  memberPhone: { color: MidnightColors.slate700, fontSize: 10, fontFamily: Fonts.inter.medium },
  grantedRowSmall: { flexDirection: 'row', gap: 6, height: 28, alignItems: 'center' },
  miniIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(212, 175, 55, 0.12)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(212, 175, 55, 0.18)' },
  memberActions: { alignItems: 'flex-end', justifyContent: 'center', height: '100%', gap: 4 },
  memberNumber: { color: MidnightColors.gold, fontSize: 10, fontFamily: Fonts.inter.bold, opacity: 0.5 },
  memberDelete: { padding: 8 },

  grantedRow: { flexDirection: 'row', gap: 6, marginTop: 12 },
  grantedIcon: { width: 22, height: 22, borderRadius: 11, backgroundColor: 'rgba(212, 175, 55, 0.1)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(212, 175, 55, 0.2)' },

  // Premium Permission Modal
  premiumModalBackdrop: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(2, 6, 23, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000
  },
  premiumModalContent: {
    width: SCREEN_WIDTH * 0.85,
    alignSelf: 'center',
    borderRadius: 32,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10
  },
  premiumModalHeader: { flexDirection: 'row', alignItems: 'center', padding: 20, backgroundColor: 'rgba(255,255,255,0.02)' },
  premiumAvatar: { width: 48, height: 48, borderRadius: 24, overflow: 'hidden' },
  avatarGradient: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  premiumAvatarText: { color: MidnightColors.background, fontSize: 20, fontFamily: Fonts.outfit.extraBold },
  premiumModalTitle: { color: '#fff', fontSize: 18, fontFamily: Fonts.outfit.bold },
  premiumModalSub: { color: MidnightColors.gold, fontSize: 10, fontFamily: Fonts.inter.bold, textTransform: 'uppercase', marginTop: 1, opacity: 0.8 },
  closeModalCircle: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.05)', alignItems: 'center', justifyContent: 'center' },
  permissionsScroll: { padding: 16 },
  permissionsGroupLabel: { color: MidnightColors.slate700, fontSize: 10, fontFamily: Fonts.inter.bold, textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 12, marginLeft: 4 },
  userInfoToggle: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.025)', padding: 10, borderRadius: 14, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.04)', gap: 10 },
  userInfoToggleActive: { backgroundColor: 'rgba(212, 175, 55, 0.06)', borderColor: 'rgba(212, 175, 55, 0.18)' },
  userInfoToggleIcon: { width: 30, height: 30, borderRadius: 10, backgroundColor: 'rgba(212, 175, 55, 0.1)', alignItems: 'center', justifyContent: 'center' },
  userInfoToggleTitle: { color: '#fff', fontSize: 13, fontFamily: Fonts.outfit.bold },
  userInfoToggleSub: { color: '#94a3b8', fontSize: 10, fontFamily: Fonts.inter.medium, marginTop: 1 },
  userInfoPanel: { backgroundColor: 'rgba(255,255,255,0.025)', borderRadius: 16, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)', padding: 10, marginBottom: 10 },
  userInfoProfileRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  userInfoLargeAvatar: { width: 44, height: 44, borderRadius: 22, overflow: 'hidden' },
  memberInfoAvatarImage: { width: '100%', height: '100%' },
  userInfoName: { color: '#fff', fontSize: 14, fontFamily: Fonts.outfit.bold },
  userInfoHandle: { color: MidnightColors.gold, fontSize: 11, fontFamily: Fonts.inter.bold, marginTop: 2 },
  userInfoDetails: { gap: 6 },
  userInfoDetailRow: { backgroundColor: 'rgba(15, 23, 42, 0.7)', padding: 9, borderRadius: 12 },
  userInfoDetailLabel: { color: '#94a3b8', fontSize: 9, fontFamily: Fonts.inter.bold, textTransform: 'uppercase', marginBottom: 2, letterSpacing: 0.8 },
  userInfoDetailValue: { color: '#fff', fontSize: 12, fontFamily: Fonts.inter.medium },
  richPermCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.02)', padding: 12, borderRadius: 20, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.03)', gap: 12 },
  richPermCardActive: { backgroundColor: 'rgba(212, 175, 55, 0.05)', borderColor: 'rgba(212, 175, 55, 0.2)' },
  richPermIconBox: { width: 46, height: 46, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.08)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.06)' },
  richPermLabel: { color: MidnightColors.slate400, fontSize: 14, fontFamily: Fonts.outfit.bold },
  richPermDesc: { color: MidnightColors.slate700, fontSize: 10, fontFamily: Fonts.inter.medium, marginTop: 1 },
  customToggle: { width: 38, height: 20, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.1)', padding: 2, justifyContent: 'center' },
  customToggleActive: { backgroundColor: 'rgba(212, 175, 55, 0.2)' },
  customToggleThumb: { width: 16, height: 16, borderRadius: 8, backgroundColor: MidnightColors.slate400 },
  customToggleThumbActive: { backgroundColor: MidnightColors.gold, transform: [{ translateX: 18 }] },
  premiumDoneBtn: { margin: 16, marginTop: 0, borderRadius: 16, overflow: 'hidden', alignSelf: 'center', width: '60%' },
  premiumDoneGradient: { paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  premiumDoneText: { color: MidnightColors.background, fontSize: 13, fontFamily: Fonts.outfit.extraBold, textTransform: 'uppercase', letterSpacing: 1 },

  // Internal Request Cards
  requestCardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 24,
    padding: 12,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    gap: 16
  },
  requestAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(212, 175, 55, 0.1)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(212, 175, 55, 0.2)' },
  avatarTextSmall: { color: MidnightColors.gold, fontSize: 18, fontFamily: Fonts.outfit.bold },
  requestName: { color: '#fff', fontSize: 16, fontFamily: Fonts.outfit.bold },
  requestPhone: { color: MidnightColors.slate700, fontSize: 10, fontFamily: Fonts.inter.medium, marginTop: 1 },
  requestActionsMini: { flexDirection: 'row', gap: 8, paddingRight: 4 },
  miniActionBtnGreen: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#10b981', alignItems: 'center', justifyContent: 'center' },
  miniActionBtnRed: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#ef4444', alignItems: 'center', justifyContent: 'center' },

  // Request Modal Specific
  ironCladWrapper: { width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center', paddingHorizontal: 24 },
  premiumRequestModal: { width: '100%', borderRadius: 28, padding: 18, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  modalHeaderCentered: { alignItems: 'center', marginBottom: 12 },
  largeAvatar: { width: 60, height: 60, borderRadius: 30, overflow: 'hidden', marginBottom: 10 },
  largeAvatarText: { color: MidnightColors.background, fontSize: 24, fontFamily: Fonts.outfit.extraBold },
  modalRequestTitle: { color: '#fff', fontSize: 18, fontFamily: Fonts.outfit.bold, textAlign: 'center' },
  modalRequestSub: { color: MidnightColors.slate400, fontSize: 11, fontFamily: Fonts.inter.medium, marginTop: 2 },
  modalBody: { gap: 10, marginBottom: 14, marginTop: 14 },
  detailRow: { backgroundColor: 'rgba(255,255,255,0.03)', padding: 11, borderRadius: 16 },
  detailLabel: { color: '#94a3b8', fontSize: 9, fontFamily: Fonts.inter.bold, textTransform: 'uppercase', marginBottom: 3, letterSpacing: 0.8 },
  detailValue: { color: '#f1f5f9', fontSize: 13, fontFamily: Fonts.inter.medium },
  modalFooter: { flexDirection: 'row', gap: 10 },
  modalActionBtn: { flex: 1, paddingVertical: 12, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  modalActionBtnApprove: { flex: 1, borderRadius: 14, overflow: 'hidden' },
  approveGradient: { flex: 1, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  modalActionText: { fontSize: 13, fontFamily: Fonts.outfit.bold },
  modalActionTextWhite: { color: '#fff', fontSize: 13, fontFamily: Fonts.outfit.bold },
  modalCloseLink: { marginTop: 12, alignSelf: 'center' },
  modalCloseLinkText: { color: MidnightColors.slate400, fontSize: 12, fontFamily: Fonts.inter.medium },

  // Design
  designCard: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between', 
    backgroundColor: 'rgba(30, 41, 59, 0.45)', 
    paddingVertical: 12, 
    paddingHorizontal: 16, 
    borderRadius: 14, 
    borderWidth: 1, 
    borderColor: 'rgba(255, 255, 255, 0.04)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2
  },
  designInfo: { flex: 1, paddingRight: 12 },
  designLabel: { color: MidnightColors.slate400, fontSize: 9.5, fontFamily: Fonts.inter.medium, textTransform: 'uppercase', letterSpacing: 0.5 },
  designValue: { color: '#fff', fontSize: 14, fontFamily: Fonts.outfit.semiBold, marginTop: 2 },

  // Guest Access
  guestSection: { backgroundColor: MidnightColors.deepSlate, padding: 24, borderRadius: 28, borderWidth: 1, borderColor: MidnightColors.cardBorder },
  guestTitle: { fontSize: 20, color: '#fff', fontFamily: Fonts.outfit.bold, textAlign: 'center' },
  guestSub: { fontSize: 13, color: MidnightColors.slate400, fontFamily: Fonts.inter.regular, textAlign: 'center', marginTop: 4, marginBottom: 20 },
  input: { backgroundColor: 'rgba(255,255,255,0.05)', padding: 16, borderRadius: 12, color: '#fff', fontFamily: Fonts.inter.regular, marginBottom: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  accessBtn: { backgroundColor: MidnightColors.gold, paddingVertical: 16, borderRadius: 16, alignItems: 'center', marginTop: 8 },
  accessBtnText: { fontSize: 15, color: MidnightColors.background, fontFamily: Fonts.outfit.extraBold, textTransform: 'uppercase' },

  // Gallery Btn
  viewGalleryBtn: { height: 60, borderRadius: 20, overflow: 'hidden', marginTop: 10 },
  viewGalleryGradient: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
  viewGalleryText: { fontSize: 16, color: MidnightColors.background, fontFamily: Fonts.outfit.extraBold, textTransform: 'uppercase' },

  // Modal
  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.8)' },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    width: '100%'
  },
  modalContent: { backgroundColor: '#0f172a', width: '100%', borderRadius: 28, padding: 24, borderWidth: 1, borderColor: 'rgba(212,175,55,0.2)' },
  modalTitle: { fontSize: 24, color: '#fff', fontFamily: Fonts.outfit.bold },
  templateModalSub: { color: MidnightColors.slate400, fontSize: 13, fontFamily: Fonts.inter.medium, marginTop: -10, marginBottom: 18 },
  submitBtn: { backgroundColor: MidnightColors.gold, padding: 16, borderRadius: 16, alignItems: 'center', marginTop: 8 },
  submitBtnText: { color: MidnightColors.background, fontSize: 16, fontFamily: Fonts.outfit.bold },

  templateOption: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 20, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 16, marginBottom: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  activeTemplate: { backgroundColor: MidnightColors.gold },
  templateText: { color: '#fff', fontSize: 15, fontFamily: Fonts.outfit.bold },
  activeTemplateText: { color: MidnightColors.background },
  templateRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 10,
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  activeTemplateRowCard: {
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  templateRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  palettePreview: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  paletteAccentDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  templateRowText: {
    flex: 1,
    marginRight: 8,
  },
  templateRowName: {
    color: '#fff',
    fontSize: 14,
    fontFamily: Fonts.outfit.bold,
  },
  templateRowDesc: {
    color: MidnightColors.slate400,
    fontSize: 11,
    fontFamily: Fonts.inter.regular,
    marginTop: 1,
  },
  templateCheckCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },

  errorText: { color: '#fff', fontSize: 18, fontFamily: Fonts.outfit.bold, marginBottom: 20 },
  backBtn: { paddingHorizontal: 20, paddingVertical: 10, backgroundColor: MidnightColors.gold, borderRadius: 10 },
  backBtnText: { color: MidnightColors.background, fontWeight: 'bold' },

  // Share Modal
  shareModalContent: { backgroundColor: '#0f172a', width: '90%', borderRadius: 32, padding: 24, borderWidth: 1, borderColor: 'rgba(212,175,55,0.2)', alignItems: 'center' },
  qrContainer: { backgroundColor: '#fff', padding: 20, borderRadius: 24, marginTop: 10, alignItems: 'center' },
  qrCode: { width: 180, height: 180 },
  qrLabel: { color: MidnightColors.background, fontSize: 12, fontFamily: Fonts.inter.bold, marginTop: 10, textTransform: 'uppercase' },
  joinIdContainer: { marginTop: 24, width: '100%', alignItems: 'center' },
  joinIdLabel: { color: MidnightColors.slate400, fontSize: 12, fontFamily: Fonts.inter.bold, textTransform: 'uppercase', marginBottom: 8 },
  joinIdBox: { backgroundColor: 'rgba(255,255,255,0.05)', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(212,175,55,0.3)' },
  joinIdValue: { color: MidnightColors.gold, fontSize: 24, fontFamily: Fonts.outfit.extraBold, letterSpacing: 4 },
  shareActionBtn: { backgroundColor: MidnightColors.gold, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 16, paddingHorizontal: 32, borderRadius: 20, marginTop: 32, width: '100%', justifyContent: 'center' },
  shareActionText: { color: MidnightColors.background, fontSize: 16, fontFamily: Fonts.outfit.extraBold, textTransform: 'uppercase' },
  closeModalBtn: { marginTop: 16, padding: 10 },
  closeModalText: { color: MidnightColors.slate400, fontSize: 14, fontFamily: Fonts.inter.medium },
};
