import { StyleSheet, Dimensions, Platform } from 'react-native';
import { MidnightColors, Fonts } from '../../constants/theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const bohemianStyles = {
// Bohemian Rhapsody styles
  bohemianBgLinesContainer: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
  },
  bohemianBgLine: {
    width: 1,
    height: '100%',
    backgroundColor: '#fff',
  },
  bohemianTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 40,
    marginBottom: 5,
  },
  bohemianHeaderButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#431407',
    backgroundColor: '#fffbeb',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#431407',
    shadowOffset: { width: 1.5, height: 1.5 },
    shadowOpacity: 0.85,
    shadowRadius: 0,
    elevation: 2,
  },
  bohemianDateBadge: {
    height: 38,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#431407',
    backgroundColor: '#fffbeb',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#431407',
    shadowOffset: { width: 1.5, height: 1.5 },
    shadowOpacity: 0.85,
    shadowRadius: 0,
    elevation: 2,
  },
  bohemianHeaderDate: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.8,
    textAlign: 'center',
  },
  bohemianLabel: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  bohemianAlbumContainer: {
    height: 310,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -15,
    marginBottom: 10,
    position: 'relative',
  },
  bohemianPulseRing: {
    position: 'absolute',
    width: 270,
    height: 270,
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: 'rgba(251, 146, 60, 0.25)',
    marginRight: 90,
    zIndex: 0,
    top: 20,
  },
  bohemianVinylRecord: {
    position: 'absolute',
    width: 240,
    height: 240,
    right: '2%',
    zIndex: 1,
    top: 35,
  },
  bohemianVinylDisc: {
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#090909',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#222',
  },
  bohemianVinylGroove1: {
    position: 'absolute',
    width: 190,
    height: 190,
    borderRadius: 95,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  bohemianVinylGroove2: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  bohemianVinylGroove3: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  bohemianVinylSheenLine1: {
    position: 'absolute',
    width: 15,
    height: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    transform: [{ rotate: '45deg' }],
  },
  bohemianVinylSheenLine2: {
    position: 'absolute',
    width: 30,
    height: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    transform: [{ rotate: '135deg' }],
  },
  bohemianVinylCenterLabel: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#fb923c',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bohemianVinylCenterRing: {
    position: 'absolute',
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  bohemianVinylCenterHole: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  bohemianAlbumSleeve: {
    width: 270,
    height: 270,
    borderRadius: 30,
    overflow: 'hidden',
    zIndex: 2,
    marginRight: 90,
    backgroundColor: '#3f2f26',
  },
  bohemianSleeveInnerBorder: {
    position: 'absolute',
    top: 8,
    left: 8,
    right: 8,
    bottom: 8,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    zIndex: 3,
  },
  bohemianSleeveImage: {
    width: '100%',
    height: '100%',
  },
  bohemianSleeveBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  bohemianSleeveBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  bohemianHudContainer: {
    paddingHorizontal: 24,
    marginTop: 15,
    marginBottom: 20,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  bohemianTrackInfo: {
    alignItems: 'center',
    marginBottom: 16,
    alignSelf: 'stretch',
  },
  bohemianTrackTitle: {
    fontSize: 32,
    lineHeight: 38,
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: -0.5,
    paddingHorizontal: 12,
    alignSelf: 'stretch',
    flexShrink: 1,
  },
  bohemianTrackHost: {
    fontSize: 13,
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  bohemianScrubberContainer: {
    alignSelf: 'stretch',
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  bohemianScrubberTimeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  bohemianScrubberTime: {
    fontSize: 11,
    fontWeight: '600',
  },
  bohemianScrubberTrack: {
    height: 4,
    borderRadius: 2,
    position: 'relative',
    justifyContent: 'center',
  },
  bohemianScrubberProgress: {
    height: '100%',
    borderRadius: 2,
    width: '35%',
  },
  bohemianScrubberPlayhead: {
    width: 10,
    height: 10,
    borderRadius: 5,
    position: 'absolute',
    left: '35%',
    transform: [{ translateX: -5 }],
  },
  bohemianControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 32,
  },
  bohemianControlBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bohemianPlayBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  bohemianVisitorTab: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#431407',
    backgroundColor: '#fffbeb',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    shadowColor: '#431407',
    shadowOffset: { width: 1.5, height: 1.5 },
    shadowOpacity: 0.85,
    shadowRadius: 0,
    elevation: 2,
  },
  bohemianVisitorTabActive: {
    backgroundColor: '#fed7aa',
    borderWidth: 2,
    borderColor: '#431407',
    shadowColor: '#431407',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  bohemianEqContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 12,
    gap: 2,
    marginLeft: 6,
  },
  bohemianEqBar: {
    width: 2,
    height: '100%',
    borderRadius: 1,
  },
  bohemianTabsDividerContainer: {
    paddingHorizontal: 20,
    marginTop: 15,
    marginBottom: 10,
  },
  bohemianDividerContainer: {
    paddingHorizontal: 20,
    marginVertical: 15,
  },
  bohemianGuitarString: {
    borderRadius: 999,
  },
  bohemianPhotoTile: {
    shadowColor: '#431407',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  bohemianGalleryImg: {
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
  },
  bohemianPhotoLabelContainer: {
    width: '100%',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopWidth: 0.5,
  },
  bohemianPhotoLabelText: {
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  bohemianPhotoSubtext: {
    fontSize: 11,
    textAlign: 'center',
    opacity: 0.8,
  },
};
