import { StyleSheet, Dimensions, Platform } from 'react-native';
import { MidnightColors, Fonts } from '../../constants/theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const brutalistStyles = {
// Brutalist Theme Styles
  brutalistHeroStage: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 26,
    overflow: 'hidden',
    backgroundColor: '#efede7',
  },
  brutalistHeroBackdrop: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.9,
  },
  brutalistGridTexture: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.85,
  },
  brutalistGridLine: {
    position: 'absolute',
    top: 72,
    bottom: 36,
    width: 1,
    backgroundColor: 'rgba(255, 255, 250, 0.14)',
  },
  brutalistGridLineVerticalOne: {
    left: 38,
  },
  brutalistGridLineVerticalTwo: {
    right: 112,
  },
  brutalistGridLineHorizontal: {
    position: 'absolute',
    left: 18,
    right: 18,
    height: 1,
    backgroundColor: 'rgba(17, 17, 19, 0.12)',
  },
  brutalistGridLineHorizontalOne: {
    top: 168,
  },
  brutalistGridLineHorizontalTwo: {
    bottom: 178,
  },
  brutalistHeaderRail: {
    position: 'absolute',
    top: 96,
    left: 22,
    right: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 11,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 250, 0.2)',
  },
  brutalistHeaderRailText: {
    color: '#fffffa',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2.1,
  },
  brutalistHeaderRailCode: {
    color: '#c2a76d',
    fontSize: 10,
    fontFamily: Fonts.spaceGrotesk.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  brutalistArtworkBlock: {
    position: 'absolute',
    top: 145,
    right: 18,
    width: 182,
    height: 218,
    backgroundColor: '#fffffa',
    padding: 8,
    borderRadius: 8,
    shadowColor: '#111113',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.26,
    shadowRadius: 28,
    elevation: 7,
  },
  brutalistArtworkImage: {
    width: '100%',
    height: '100%',
    borderRadius: 4,
  },
  brutalistArtworkCaption: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: 'rgba(255, 255, 250, 0.9)',
  },
  brutalistArtworkCaptionNumber: {
    color: '#111113',
    fontSize: 18,
    lineHeight: 20,
    fontFamily: Fonts.spaceGrotesk.bold,
  },
  brutalistArtworkCaptionText: {
    color: '#62625d',
    fontSize: 8,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  brutalistHeroCard: {
    width: '86%',
    alignSelf: 'flex-start',
    paddingHorizontal: 22,
    paddingVertical: 22,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 250, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(17, 17, 19, 0.08)',
    shadowColor: '#111113',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.14,
    shadowRadius: 28,
    elevation: 6,
  },
  brutalistHeroLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  brutalistHeroLabel: {
    color: '#8f6d32',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  brutalistHeroLabelLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(17, 17, 19, 0.18)',
  },
  brutalistHeroTitle: {
    color: '#111113',
    fontSize: 43,
    lineHeight: 42,
    fontFamily: Fonts.spaceGrotesk.bold,
  },
  brutalistHeroMetaRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  brutalistHeroDate: {
    flex: 1,
    color: '#62625d',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  brutalistHeroShare: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#111113',
  },
  brutalistHeroShareText: {
    color: '#fffffa',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  brutalistHeroMarker: {
    position: 'absolute',
    right: 24,
    bottom: 30,
    width: 54,
    height: 54,
    borderRadius: 12,
    backgroundColor: '#111113',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brutalistHeroMarkerText: {
    color: '#fffffa',
    fontSize: 9,
    fontFamily: Fonts.spaceGrotesk.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  brutalistFloatingButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(17, 17, 19, 0.92)',
    borderColor: 'rgba(143, 109, 50, 0.62)',
    borderWidth: 1,
    shadowColor: '#111113',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 4,
  },
  brutalistVisitorHeaderContainer: {
    height: 68,
    marginTop: -8,
    marginBottom: 8,
    backgroundColor: '#efede7',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(17, 17, 19, 0.08)',
  },
  brutalistVisitorHeaderContent: {
    paddingHorizontal: 18,
    alignItems: 'center',
    gap: 10,
  },
  brutalistVisitorTab: {
    minHeight: 38,
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 250, 0.86)',
    borderWidth: 1,
    borderColor: 'rgba(17, 17, 19, 0.12)',
    shadowColor: '#111113',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 14,
    elevation: 1,
  },
  brutalistVisitorTabActive: {
    backgroundColor: '#111113',
    borderColor: '#111113',
    shadowOpacity: 0.16,
    elevation: 4,
  },
  brutalistVisitorTabText: {
    color: '#111113',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.35,
  },
  brutalistVisitorTabTextActive: {
    color: '#fffffa',
  },
  brutalistInfoBox: {
    marginHorizontal: 18,
    marginTop: 18,
    marginBottom: 18,
    padding: 0,
    borderWidth: 0,
    backgroundColor: '#fffffa',
    shadowColor: '#111113',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.08,
    shadowRadius: 30,
    elevation: 4,
  },
  brutalistInfoInner: {
    paddingHorizontal: 22,
    paddingVertical: 22,
    borderLeftWidth: 5,
    borderLeftColor: '#111113',
  },
  brutalistInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  brutalistInfoKicker: {
    color: '#111113',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.8,
  },
  brutalistInfoLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(17, 17, 19, 0.18)',
  },
  brutalistInfoCode: {
    color: '#8f6d32',
    fontSize: 9,
    fontFamily: Fonts.spaceGrotesk.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  brutalistVisitorDescription: {
    color: '#2f2f2d',
    fontSize: 15,
    lineHeight: 24,
    fontFamily: Fonts.inter.regular,
    textAlign: 'left',
  },
  brutalistGalleryHeader: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    alignItems: 'flex-end',
  },
  brutalistGalleryTitle: {
    color: '#111113',
    fontSize: 32,
    lineHeight: 34,
    fontFamily: Fonts.spaceGrotesk.bold,
    letterSpacing: 0,
  },
  brutalistGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 12,
    marginBottom: 10,
  },
  brutalistGalleryKickerText: {
    color: '#111113',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.9,
  },
  brutalistGalleryKickerLine: {
    width: 44,
    height: 1,
    backgroundColor: 'rgba(17, 17, 19, 0.2)',
  },
  brutalistGalleryKickerCode: {
    color: '#8f6d32',
    fontSize: 9,
    fontFamily: Fonts.spaceGrotesk.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  brutalistPhotoCount: {
    color: '#62625d',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  brutalistPhotoTile: {
    borderWidth: 1,
    borderColor: 'rgba(17, 17, 19, 0.1)',
    borderRadius: 14,
    padding: 6,
    backgroundColor: '#fffffa',
    shadowColor: '#111113',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 3,
  },
  brutalistPhotoTileFeatured: {
    borderTopWidth: 5,
    borderTopColor: '#111113',
  },
  brutalistPhotoTileNarrow: {
    borderBottomWidth: 4,
    borderBottomColor: '#8f6d32',
  },
  brutalistPhotoLabel: {
    position: 'absolute',
    left: 12,
    top: 12,
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(17, 17, 19, 0.9)',
  },
  brutalistPhotoLabelNumber: {
    color: '#fffffa',
    fontSize: 11,
    fontFamily: Fonts.spaceGrotesk.bold,
  },
  brutalistPhotoLabelText: {
    color: '#d1c4a5',
    fontSize: 8,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  brutalistGalleryImg: {
    borderRadius: 9,
  },
};
