import { StyleSheet, Dimensions, Platform } from 'react-native';
import { MidnightColors, Fonts } from '../../constants/theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const classicStyles = {
// Premium Classic White Fine Art Styles
  classicDividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginVertical: 24,
    alignSelf: 'center',
    width: '60%',
  },
  classicDividerLine: {
    flex: 1,
    height: 1,
    opacity: 0.2,
  },
  classicDividerDot: {
    fontSize: 8,
    opacity: 0.8,
  },
  classicHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 100,
    paddingBottom: 40,
  },
  classicFrame: {
    position: 'absolute',
    top: 60,
    bottom: 30,
    left: 20,
    right: 20,
    borderWidth: 1,
    borderRadius: 0, // Clean, zero-radius classic framing
    pointerEvents: 'none',
  },
  classicHeroImageContainer: {
    position: 'absolute',
    top: 80,
    left: 28,
    right: 28,
    height: SCREEN_WIDTH * 1.15, // Grand portrait exhibition height!
    borderRadius: 2,
    overflow: 'hidden',
    borderWidth: 1.5, // Thicker, luxurious outer frame
    borderColor: '#cca43b', // Elegantly gilded warm gold frame holding the white-matted photo!
    backgroundColor: '#ffffff', // Crisp white internal gallery matte frame
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    padding: 10, // Gives a beautiful physical matting effect around the photograph
  },
  classicHeroImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  classicCenterContent: {
    position: 'absolute',
    top: 80 + SCREEN_WIDTH * 1.15 + 20, // Mathematically scales perfectly below the enlarged portrait mat card
    left: 30,
    right: 30,
    alignItems: 'center',
  },
  classicTitle: {
    fontSize: 32,
    fontFamily: Fonts.serif,
    textAlign: 'center',
    marginHorizontal: 36,
    lineHeight: 42,
    letterSpacing: 1.5,
    textTransform: 'capitalize',
  },
  classicDividerOrnament: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    width: 60,
  },
  classicDividerOrnamentLine: {
    flex: 1,
    height: 1,
    opacity: 0.4,
  },
  classicDividerOrnamentDot: {
    fontSize: 6,
    opacity: 0.7,
  },
  classicDateText: {
    fontSize: 12,
    fontFamily: Fonts.serif,
    fontStyle: 'italic',
    marginTop: 10,
    letterSpacing: 2,
  },
  classicButton: {
    marginTop: 28,
    borderWidth: 1,
    borderRadius: 0, // Perfectly square classic high-fashion button
    paddingHorizontal: 24,
    paddingVertical: 10,
    alignSelf: 'center',
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  classicButtonText: {
    fontSize: 11,
    fontFamily: Fonts.inter.bold,
    letterSpacing: 2,
  },
  classicBottomContent: {
    position: 'absolute',
    bottom: 25,
    left: 30,
    right: 30,
    alignItems: 'center',
    gap: 8,
  },
  classicBrandLogoScript: {
    fontFamily: Fonts.serif,
    fontSize: 16,
    fontStyle: 'italic',
    marginTop: 2,
  },
  classicBrandSubText: {
    fontSize: 8,
    fontFamily: Fonts.inter.bold,
    letterSpacing: 2,
  },
  classicChevron: {
    opacity: 0.85,
    marginTop: 8,
  },
  classicActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 24,
    width: '100%',
  },
  classicSideButton: {
    width: 38,
    height: 38,
    borderWidth: 1,
    borderRadius: 0, // Clean, high-fashion square buttons
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  heroHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 100,
    paddingBottom: 40,
  },
  heroGlassCard: {
    position: 'absolute',
    bottom: 110,
    left: SCREEN_WIDTH * 0.08,
    right: SCREEN_WIDTH * 0.08,
    paddingHorizontal: 24,
    paddingVertical: 28,
    borderRadius: 2, // Ultra-modern sharp editorial edges
    backgroundColor: 'rgba(10, 10, 12, 0.7)', // Luminous dark obsidian glass
    borderWidth: 0.8, // Micro-thin gold border
    borderColor: 'rgba(204, 164, 59, 0.35)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
    alignItems: 'center',
  },
  heroBadge: {
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderWidth: 0.8,
    borderColor: 'rgba(204, 164, 59, 0.35)',
    borderRadius: 2,
    marginBottom: 16,
  },
  heroBadgeText: {
    fontFamily: Fonts.inter.bold,
    fontSize: 9,
    color: '#cca43b',
    letterSpacing: 3, // Premium wide letterspacing
  },
  heroTitleMain: {
    fontSize: 28,
    textAlign: 'center',
    color: '#ffffff',
    letterSpacing: 1.5,
    lineHeight: 38,
  },
  heroDividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginVertical: 14,
    width: 140,
  },
  heroDividerLine: {
    flex: 1,
    height: 0.8,
    backgroundColor: 'rgba(204, 164, 59, 0.25)',
  },
  heroDividerStar: {
    fontSize: 10,
    color: '#cca43b',
  },
  heroDateMain: {
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    color: '#94a3b8',
    letterSpacing: 3,
  },
  heroActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    marginTop: 26,
    width: '100%',
  },
  heroSideButton: {
    width: 44,
    height: 44,
    borderWidth: 0.8,
    borderColor: '#cca43b',
    borderRadius: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  heroEnterButton: {
    flex: 1,
    height: 44,
    backgroundColor: '#cca43b',
    borderRadius: 2,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#cca43b',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  heroEnterButtonText: {
    fontSize: 11,
    fontFamily: Fonts.inter.bold,
    letterSpacing: 2,
    color: '#000000',
  },
  heroBottomContent: {
    position: 'absolute',
    bottom: 25,
    left: 30,
    right: 30,
    alignItems: 'center',
    gap: 6,
  },
  heroBrandText: {
    fontSize: 8,
    fontFamily: Fonts.inter.bold,
    letterSpacing: 2,
    color: 'rgba(255, 255, 255, 0.35)',
  },
  heroChevron: {
    opacity: 0.85,
    marginTop: 4,
  },
  categoryOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  activeCategoryOption: {
    backgroundColor: 'rgba(212, 175, 55, 0.08)',
    borderColor: 'rgba(212, 175, 55, 0.35)',
  },
  categoryLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  categoryIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryText: {
    color: '#cbd5e1',
    fontSize: 14,
    fontFamily: Fonts.inter.medium,
  },
  activeCategoryText: {
    color: MidnightColors.gold,
    fontFamily: Fonts.inter.bold,
  },
  categoryCheckBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: MidnightColors.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  coverControlRow: {
    position: 'absolute',
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,0,0,0.65)',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    zIndex: 15,
  },
  coverControlSubBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  coverControlText: {
    color: '#fff',
    fontSize: 11,
    fontFamily: Fonts.inter.bold,
  },
  repositionToolbar: {
    position: 'absolute',
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(0,0,0,0.85)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    zIndex: 30,
  },
  repositionInstruction: {
    color: '#fff',
    fontSize: 12,
    fontFamily: Fonts.inter.medium,
  },
  repositionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  repositionBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  repositionCancelBtn: {
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  repositionSaveBtn: {
    backgroundColor: MidnightColors.gold,
  },
  repositionBtnText: {
    color: '#fff',
    fontSize: 11,
    fontFamily: Fonts.inter.bold,
  },
  toastContainer: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 20,
    alignItems: 'center',
    zIndex: 9999,
  },
  toastContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(9, 8, 24, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.35)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  toastText: {
    color: '#ffffff',
    fontSize: 13,
    fontFamily: Fonts.inter.bold,
  },
  zoomControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  zoomBtn: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  zoomText: {
    color: '#fff',
    fontSize: 11,
    fontFamily: Fonts.inter.bold,
    minWidth: 32,
    textAlign: 'center',
  },

  etherealHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  etherealOverlayContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  etherealBackBtnRound: {
    position: 'absolute',
    top: 50,
    left: 20,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  etherealShareBtnRound: {
    position: 'absolute',
    top: 50,
    right: 20,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  etherealDetailsCard: {
    position: 'absolute',
    bottom: 30,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 24,
    paddingVertical: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  etherealEnterBtn: {
    width: '100%',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  etherealEnterBtnText: {
    color: '#ffffff',
    fontSize: 12,
    letterSpacing: 2,
    fontWeight: 'bold',
    fontFamily: Fonts.inter.bold,
  },
  etherealBrandSection: {
    alignItems: 'center',
    marginBottom: 12,
  },
  etherealBrandScriptText: {
    fontSize: 18,
    fontStyle: 'italic',
    color: '#2d2a29',
    textAlign: 'center',
    marginBottom: 4,
  },
  etherealMonogramRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  etherealMonogramCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#2d2a29',
    justifyContent: 'center',
    alignItems: 'center',
  },
  etherealMonogramLetter: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#2d2a29',
  },
  etherealSocialRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    marginBottom: 20,
  },
  etherealSocialIconBtn: {
    padding: 4,
  },
  etherealCoupleNames: {
    fontSize: 22,
    letterSpacing: 2,
    textAlign: 'center',
    marginBottom: 14,
  },
  etherealCountsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  etherealCountItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  etherealCountText: {
    fontSize: 14,
    color: '#555555',
    fontWeight: '500',
  },
};
