import { StyleSheet, Dimensions, Platform } from 'react-native';
import { MidnightColors, Fonts } from '../../constants/theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const cyberTechStyles = {
// CYBER TECH TEMPLATE STYLES

  neonCarnivalHeroOverlay: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#0c0714',
    zIndex: 2,
    justifyContent: 'space-between',
  },
  neonCarnivalTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    zIndex: 10,
  },
  neonCarnivalHeaderButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(24, 15, 38, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(217, 70, 239, 0.2)',
  },
  neonCarnivalContent: {
    paddingHorizontal: 24,
    alignItems: 'center',
    marginTop: 20,
    zIndex: 10,
  },
  neonCarnivalDateText: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 14,
    color: '#d8b4fe',
    letterSpacing: 3,
    marginBottom: 8,
  },
  neonCarnivalTitleWrapper: {
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  neonCarnivalTitle: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 48,
    color: '#faf5ff',
    textAlign: 'center',
    textShadowColor: 'rgba(217, 70, 239, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
  },
  neonCarnivalCoverWrapper: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  neonCarnivalCoverImg: {
    width: '100%',
    height: '100%',
    opacity: 0.8,
  },
  neonCarnivalGradient: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    bottom: 0,
  },
  neonCarnivalInfoBox: {
    backgroundColor: 'rgba(20, 12, 33, 0.72)',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: 'rgba(217, 70, 239, 0.25)',
    padding: 12,
    shadowColor: '#d946ef',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 6,
  },
  neonCarnivalInfoInner: {
    borderWidth: 1,
    borderColor: 'rgba(217, 70, 239, 0.15)',
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    backgroundColor: 'rgba(12, 7, 20, 0.5)',
  },
  neonCarnivalInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
    justifyContent: 'center',
  },
  neonCarnivalInfoPulse: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#d946ef',
    shadowColor: '#d946ef',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 6,
  },
  neonCarnivalInfoKicker: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 12,
    color: '#d946ef',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  neonCarnivalInfoLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(217, 70, 239, 0.2)',
    marginLeft: 8,
  },
  neonCarnivalVisitorDescription: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 14,
    lineHeight: 22,
    color: '#d8b4fe',
    textAlign: 'center',
  },
  neonCarnivalPartnersTitle: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 26,
    color: '#faf5ff',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(217, 70, 239, 0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  neonCarnivalPartnersSubtitle: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 13,
    color: '#d8b4fe',
    textAlign: 'center',
    lineHeight: 20,
    letterSpacing: 0.5,
  },
  neonCarnivalPartnerCard: {
    backgroundColor: 'rgba(20, 12, 33, 0.8)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(217, 70, 239, 0.15)',
    padding: 16,
    shadowColor: '#d946ef',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  neonCarnivalEmptyText: {
    fontFamily: 'TiltNeon_400Regular',
    color: '#d8b4fe',
    fontSize: 14,
    letterSpacing: 1,
  },
  neonCarnivalPartnerName: {
    fontFamily: 'TiltNeon_400Regular',
    color: '#faf5ff',
    fontSize: 18,
    letterSpacing: 0.5,
  },
  neonCarnivalPartnerType: {
    fontFamily: 'TiltNeon_400Regular',
    color: '#d946ef',
    fontSize: 12,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  neonCarnivalGalleryHeader: {},
  neonCarnivalGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  neonCarnivalGalleryPulse: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#d946ef',
    shadowColor: '#d946ef',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  neonCarnivalGalleryKickerText: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 11,
    color: '#d946ef',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  neonCarnivalGalleryKickerLine: {
    width: 40,
    height: 1,
    backgroundColor: 'rgba(217, 70, 239, 0.3)',
  },
  neonCarnivalGalleryTitle: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 24,
    color: '#faf5ff',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(217, 70, 239, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  neonCarnivalPhotoCount: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 12,
    color: '#d8b4fe',
    letterSpacing: 1,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  neonCarnivalPhotoTile: {
    borderWidth: 1.5,
    borderRadius: 16,
    padding: 0,
    backgroundColor: 'rgba(20, 12, 33, 0.8)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 4,
    overflow: 'hidden',
  },
  neonCarnivalPhotoTileFeatured: {
    borderWidth: 2,
    shadowOpacity: 0.5,
    shadowRadius: 14,
    elevation: 6,
  },
  neonCarnivalGalleryImg: {
    borderRadius: 14,
  },
  neonCarnivalViewerActionCount: {
    fontFamily: 'TiltNeon_400Regular',
    color: '#d8b4fe',
  },
  neonCarnivalText: {
    fontFamily: 'TiltNeon_400Regular',
  },
  cyberHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#05070c',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    paddingBottom: 24,
  },
  cyberGridLines: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderColor: 'rgba(0, 240, 255, 0.03)',
  },
  cyberGlowDot1: {
    position: 'absolute',
    top: '15%',
    left: '-10%',
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: '#00f0ff',
    opacity: 0.06,
  },
  cyberGlowDot2: {
    position: 'absolute',
    bottom: '20%',
    right: '-10%',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: '#d946ef',
    opacity: 0.05,
  },
  cyberTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderColor: 'rgba(0, 240, 255, 0.15)',
  },
  cyberPathText: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 22,
    color: '#00f0ff',
    letterSpacing: 1.5,
    textAlign: 'center',
  },
  cyberHeaderButton: {
    width: 36,
    height: 36,
    borderRadius: 6,
    backgroundColor: 'rgba(0, 240, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(0, 240, 255, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cyberTitleContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 12,
  },
  cyberMiddleFrame: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 16,
  },
  cyberPosterWrapper: {
    width: '100%',
    aspectRatio: 3 / 4,
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(0, 240, 255, 0.3)',
    backgroundColor: '#090d16',
    padding: 6,
  },
  cyberPosterImg: {
    width: '100%',
    height: '100%',
    borderRadius: 2,
  },
  cyberCorner: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderColor: '#00f0ff',
    zIndex: 5,
  },
  cyberCornerTL: {
    top: -2,
    left: -2,
    borderTopWidth: 3,
    borderLeftWidth: 3,
  },
  cyberCornerTR: {
    top: -2,
    right: -2,
    borderTopWidth: 3,
    borderRightWidth: 3,
  },
  cyberCornerBL: {
    bottom: -2,
    left: -2,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
  },
  cyberCornerBR: {
    bottom: -2,
    right: -2,
    borderBottomWidth: 3,
    borderRightWidth: 3,
  },
  cyberScanBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '35%',
    height: 2,
    backgroundColor: '#00f0ff',
    opacity: 0.6,
  },
  cyberScanStatus: {
    marginTop: 12,
    color: '#627fa7',
    fontFamily: Fonts.vt323.regular,
    fontSize: 14,
    letterSpacing: 1.2,
  },
  cyberBottomConsole: {
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 10,
    gap: 12,
  },
  cyberTerminalCard: {
    width: '100%',
    backgroundColor: 'rgba(9, 13, 22, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(0, 240, 255, 0.15)',
    borderRadius: 8,
    padding: 12,
    gap: 4,
  },
  cyberTerminalPrompt: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 16,
    color: '#e2eafc',
  },
  cyberDateContainer: {
    width: '100%',
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(0, 240, 255, 0.2)',
    borderRadius: 8,
    backgroundColor: 'rgba(0, 240, 255, 0.03)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cyberDateText: {
    color: '#00f0ff',
    fontSize: 18,
    fontFamily: Fonts.vt323.regular,
    letterSpacing: 2,
  },
};
