import { StyleSheet } from 'react-native';
import { Fonts } from '../../constants/theme';

export const executiveSuiteStyles = {
  executiveHeroStage: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 28,
    overflow: 'hidden',
    backgroundColor: '#08111f',
  },
  executiveBackdrop: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.5,
  },
  executiveHeroGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  executiveVignette: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.08)',
    margin: 14,
  },
  executiveTopBar: {
    position: 'absolute',
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 5,
  },
  executiveHeaderButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8, 17, 31, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.38)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 5,
  },
  executiveHeaderLabel: {
    color: '#e8d8b8',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2.3,
  },
  executivePortraitFrame: {
    position: 'absolute',
    top: 118,
    right: 22,
    width: 184,
    height: 228,
    borderRadius: 18,
    padding: 9,
    backgroundColor: '#f5eddc',
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.42)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.28,
    shadowRadius: 30,
    elevation: 7,
  },
  executivePortraitImage: {
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  executivePortraitOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 18,
  },
  executivePortraitCaption: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: 'rgba(8, 17, 31, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.32)',
  },
  executivePortraitCaptionText: {
    color: '#e8d8b8',
    fontSize: 9,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  executiveSealCard: {
    position: 'absolute',
    top: 238,
    left: 24,
    width: 94,
    height: 104,
    borderRadius: 16,
    backgroundColor: 'rgba(245, 237, 220, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 5,
  },
  executiveSealNumber: {
    color: '#111827',
    fontSize: 30,
    lineHeight: 32,
    fontFamily: Fonts.cormorant.bold,
  },
  executiveSealLabel: {
    color: '#9c7438',
    fontSize: 9,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  executiveHeroCard: {
    width: '94%',
    alignSelf: 'flex-start',
    paddingHorizontal: 23,
    paddingVertical: 24,
    borderRadius: 22,
    backgroundColor: 'rgba(245, 237, 220, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.34)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.18,
    shadowRadius: 32,
    elevation: 6,
  },
  executiveKickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  executiveKicker: {
    color: '#9c7438',
    fontSize: 10.5,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  executiveKickerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(156, 116, 56, 0.24)',
  },
  executiveHeroTitle: {
    color: '#111827',
    fontSize: 40,
    lineHeight: 42,
    fontFamily: Fonts.cormorant.bold,
  },
  executiveDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 17,
  },
  executiveDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(17, 24, 39, 0.18)',
  },
  executiveDividerMark: {
    width: 28,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#b89145',
  },
  executiveMetaRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  executiveDate: {
    flex: 1,
    color: '#4b5563',
    fontSize: 12,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  executiveShare: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#111827',
  },
  executiveShareText: {
    color: '#f5eddc',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  executiveVisitorHeaderContainer: {
    height: 68,
    marginTop: -8,
    marginBottom: 8,
    backgroundColor: '#08111f',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212, 180, 116, 0.18)',
  },
  executiveVisitorHeaderContent: {
    paddingHorizontal: 18,
    alignItems: 'center',
    gap: 10,
  },
  executiveVisitorTab: {
    minHeight: 38,
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: 14,
    backgroundColor: 'rgba(245, 237, 220, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.26)',
  },
  executiveVisitorTabActive: {
    backgroundColor: '#d4b474',
    borderColor: '#d4b474',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 4,
  },
  executiveVisitorTabText: {
    color: '#e8d8b8',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.35,
  },
  executiveVisitorTabTextActive: {
    color: '#111827',
  },
  executiveInfoBox: {
    marginHorizontal: 20,
    marginTop: 22,
    marginBottom: 30,
    padding: 0,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.28)',
    backgroundColor: '#f5eddc',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 4,
  },
  executiveInfoInner: {
    paddingHorizontal: 23,
    paddingVertical: 24,
  },
  executiveInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  executiveInfoMark: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#b89145',
  },
  executiveInfoKicker: {
    color: '#9c7438',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.9,
  },
  executiveInfoLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(156, 116, 56, 0.22)',
  },
  executiveVisitorDescription: {
    color: '#2f241b',
    fontSize: 15,
    lineHeight: 24.5,
    fontFamily: Fonts.inter.regular,
    textAlign: 'left',
  },
  executiveGalleryHeader: {
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 18,
  },
  executiveGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 9,
  },
  executiveGalleryKickerText: {
    color: '#d4b474',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.8,
  },
  executiveGalleryKickerLine: {
    width: 54,
    height: 1,
    backgroundColor: 'rgba(212, 180, 116, 0.32)',
  },
  executiveGalleryTitle: {
    color: '#f5eddc',
    fontSize: 36,
    lineHeight: 38,
    fontFamily: Fonts.cormorant.bold,
  },
  executivePhotoCount: {
    color: '#d4b474',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginTop: 4,
  },
  executivePhotoTile: {
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.22)',
    borderRadius: 18,
    padding: 7,
    backgroundColor: '#f5eddc',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.13,
    shadowRadius: 24,
    elevation: 3,
  },
  executivePhotoTileFeatured: {
    borderColor: 'rgba(212, 180, 116, 0.46)',
  },
  executivePhotoLabel: {
    position: 'absolute',
    left: 13,
    top: 13,
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(8, 17, 31, 0.84)',
    borderWidth: 1,
    borderColor: 'rgba(212, 180, 116, 0.28)',
  },
  executivePhotoLabelNumber: {
    color: '#f5eddc',
    fontSize: 11,
    fontFamily: Fonts.cormorant.bold,
  },
  executivePhotoLabelText: {
    color: '#d4b474',
    fontSize: 8,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  executiveGalleryImg: {
    borderRadius: 12,
  },
};
