import { StyleSheet, Dimensions, Platform } from 'react-native';
import { MidnightColors, Fonts } from '../../constants/theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const gardenStyles = {
// Garden Path Hero Overlay Styles
  gardenTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 12,
    width: '100%',
  },
  gardenHeaderButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#2E6F40',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  gardenCenterContent: {
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 24,
    marginBottom: 16,
    marginHorizontal: 20,
    // Floating translucent invite card — set bg color dynamically in JSX
    borderRadius: 24,
    borderWidth: 1,
    // borderColor set dynamically in JSX
    shadowColor: '#14532d',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 5,
  },
  gardenLeafContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(240, 253, 244, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  gardenTitle: {
    fontSize: 26,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.5,
    lineHeight: 34,
  },
  gardenDate: {
    fontSize: 13,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginTop: 6,
    fontWeight: '500',
  },
  // Garden Divider
  gardenDividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: -8,
    paddingTop: 4,
    paddingBottom: 12,
  },
  gardenDividerLine: {
    width: 48,
    height: 1,
    borderRadius: 999,
  },
  // Garden Picture Grid Card Tile & Labels
  gardenPhotoTile: {
    padding: 0,
    borderWidth: 0,
    borderRadius: 22,
    // overflow must be 'visible' (not 'hidden') so iOS renders the
    // drop shadow correctly without clipping it to the card bounds.
    overflow: 'visible',
    shadowColor: '#14532d',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.09,
    shadowRadius: 12,
    elevation: 4,
  },
  gardenGalleryImg: {
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  gardenPhotoLabelContainer: {
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopWidth: 0.5,
  },
  gardenPhotoLabelText: {
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  gardenPhotoRatioText: {
    fontFamily: Fonts.lora.semiBold,
    fontSize: 7,
    fontWeight: '600',
    letterSpacing: 1.2,
    marginTop: 1.5,
    textTransform: 'uppercase',
  },
  gardenPartnerCard: {
    borderWidth: 1,
    borderRadius: 22,
    shadowColor: '#14532d',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  gardenPartnerImage: {
    borderRadius: 32,
    borderWidth: 1.5,
  },
  // Garden Welcome Card styles
  gardenInfoBox: {
    borderWidth: 1,
    borderRadius: 22,
    padding: 12,
    shadowColor: '#14532d',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
    marginTop: 2,
    marginBottom: 20,
    marginHorizontal: 16,
  },
  gardenInfoInner: {
    borderWidth: 1,
    borderRadius: 18,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  gardenInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  gardenInfoKicker: {
    fontSize: 13,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  gardenInfoLine: {
    width: 32,
    height: 1,
    marginLeft: 8,
  },
  gardenVisitorDescription: {
    fontFamily: Fonts.lora.regular,
    fontSize: 15,
    lineHeight: 25,
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  // Garden Gallery Header styles
  gardenGalleryHeader: {
    paddingHorizontal: 20,
    marginTop: 24,
    marginBottom: 12,
  },
  gardenGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  gardenGalleryKickerText: {
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: 'lowercase',
  },
  gardenGalleryKickerLine: {
    width: 24,
    height: 1,
    borderRadius: 999,
    marginLeft: 6,
  },
  gardenGalleryTitle: {
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  gatedCard: {
    borderWidth: 1,
    padding: 12,
    marginHorizontal: 16,
    marginTop: 2,
    marginBottom: 20,
  },
  gatedInner: {
    paddingVertical: 28,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gatedContentCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  gatedIconWrapper: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  gatedTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
  },
  gatedDesc: {
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
    paddingHorizontal: 12,
  },
  gatedInput: {
    width: '100%',
    height: 50,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 16,
    marginBottom: 12,
    fontSize: 15,
  },
  gatedBtn: {
    width: '100%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  gatedBtnText: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  statusBadge: {
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 99,
  },
  statusBadgeText: {
    fontSize: 13,
    fontWeight: '600',
  },
};
