import { StyleSheet, Dimensions, Platform } from 'react-native';
import { MidnightColors, Fonts } from '../../constants/theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const museumStyles = {
// Museum Theme Styles
  museumHeroStage: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 28,
    overflow: 'hidden',
    backgroundColor: '#f3f0ea',
  },
  museumHeroVignette: {
    ...StyleSheet.absoluteFillObject,
  },
  museumWallTexture: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.55,
  },
  museumWallLine: {
    position: 'absolute',
    left: 20,
    right: 20,
    height: 1,
    backgroundColor: 'rgba(23, 32, 43, 0.065)',
  },
  museumWallLineTop: {
    top: 118,
  },
  museumWallLineMid: {
    top: 292,
    left: 58,
  },
  museumWallLineBottom: {
    bottom: 152,
    right: 80,
  },
  museumArchOutline: {
    position: 'absolute',
    top: 86,
    left: -42,
    width: 170,
    height: 260,
    borderTopLeftRadius: 86,
    borderTopRightRadius: 86,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 252, 0.18)',
    opacity: 0.88,
  },
  museumAmbientBlock: {
    position: 'absolute',
    top: 132,
    right: -50,
    width: 154,
    height: 154,
    borderRadius: 34,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 252, 0.12)',
    backgroundColor: 'rgba(255, 255, 252, 0.05)',
    transform: [{ rotate: '10deg' }],
  },
  museumPedestalBase: {
    position: 'absolute',
    top: 350,
    right: 48,
    width: 154,
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(11, 17, 24, 0.16)',
  },
  museumExhibitionRail: {
    position: 'absolute',
    top: 92,
    left: 24,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: '#9b7a44',
  },
  museumExhibitionRailText: {
    color: 'rgba(246, 243, 236, 0.86)',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  museumArtworkFrame: {
    position: 'absolute',
    top: 124,
    right: 20,
    width: 194,
    height: 240,
    borderRadius: 30,
    backgroundColor: '#fffffc',
    padding: 11,
    shadowColor: '#0b1118',
    shadowOffset: { width: 0, height: 22 },
    shadowOpacity: 0.24,
    shadowRadius: 32,
    elevation: 7,
  },
  museumArtworkImage: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  museumArtworkSheen: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 30,
  },
  museumArtworkLabel: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 17,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 252, 0.9)',
    borderWidth: 1,
    borderColor: 'rgba(23, 32, 43, 0.08)',
  },
  museumArtworkLabelIndex: {
    color: '#9b7a44',
    fontSize: 9,
    fontFamily: Fonts.spaceGrotesk.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  museumArtworkLabelText: {
    color: '#17202b',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    marginTop: 2,
  },
  museumHeroIndexCard: {
    position: 'absolute',
    top: 242,
    left: 22,
    width: 84,
    height: 98,
    borderRadius: 26,
    backgroundColor: 'rgba(23, 32, 43, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 252, 0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0b1118',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 4,
  },
  museumHeroIndexNumber: {
    color: '#f8f6ef',
    fontSize: 28,
    lineHeight: 31,
    fontFamily: Fonts.spaceGrotesk.bold,
  },
  museumHeroIndexLabel: {
    color: '#c6ad7d',
    fontSize: 9,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  museumHeroCard: {
    width: '94%',
    alignSelf: 'flex-start',
    paddingHorizontal: 22,
    paddingVertical: 23,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 252, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(23, 32, 43, 0.08)',
    shadowColor: '#0b1118',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.13,
    shadowRadius: 30,
    elevation: 5,
  },
  museumHeroKickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 13,
  },
  museumHeroKicker: {
    color: '#9b7a44',
    fontSize: 10.5,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  museumHeroKickerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(155, 122, 68, 0.2)',
  },
  museumHeroTitle: {
    color: '#17202b',
    fontSize: 40,
    lineHeight: 41,
    fontFamily: Fonts.spaceGrotesk.bold,
    letterSpacing: 0,
  },
  museumHeroDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 18,
  },
  museumHeroDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(23, 32, 43, 0.16)',
  },
  museumHeroDividerBlock: {
    width: 28,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#9b7a44',
  },
  museumHeroMetaRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  museumHeroDate: {
    flex: 1,
    color: '#596575',
    fontSize: 12,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  museumHeroMetaChip: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(155, 122, 68, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(155, 122, 68, 0.14)',
  },
  museumHeroMetaChipText: {
    color: '#7c633a',
    fontSize: 9.5,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  museumHeroShare: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#17202b',
  },
  museumHeroShareText: {
    color: '#f8f6ef',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  museumFloatingButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(23, 32, 43, 0.92)',
    borderColor: 'rgba(155, 122, 68, 0.62)',
    borderWidth: 1,
    shadowColor: '#0b1118',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 4,
  },
  museumInfoBox: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 32,
    padding: 0,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(23, 32, 43, 0.08)',
    backgroundColor: '#fffffc',
    shadowColor: '#0b1118',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.08,
    shadowRadius: 30,
    elevation: 3,
  },
  museumInfoInner: {
    paddingHorizontal: 24,
    paddingVertical: 25,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 252, 0.94)',
  },
  museumVisitorDescription: {
    color: '#3f4a56',
    fontFamily: Fonts.inter.regular,
    fontSize: 15,
    lineHeight: 25.5,
    letterSpacing: 0.05,
  },
  museumGalleryHeader: {
    marginTop: 30,
    marginBottom: 28,
    paddingHorizontal: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(23, 32, 43, 0.1)',
  },
  museumGalleryTitle: {
    color: '#17202b',
    fontSize: 34,
    lineHeight: 37,
    fontFamily: Fonts.spaceGrotesk.bold,
    letterSpacing: 0,
  },
  museumPhotoCount: {
    color: '#9b7a44',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginTop: 4,
  },
  museumGalleryImg: {
    borderRadius: 19,
  },
};
