import { StyleSheet, Dimensions, Platform } from 'react-native';
import { MidnightColors, Fonts } from '../../constants/theme';
import { FunkyFonts } from './funkyFonts';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const retroArcadeStyles = {
// RETRO ARCADE TEMPLATE STYLES
  retroHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#ffde4a',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    paddingBottom: 24,
  },
  retroTopBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 3,
    borderColor: '#231f20',
  },
  retroHeaderButtonBack: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ff3562',
    borderWidth: 3,
    borderColor: '#231f20',
    justifyContent: 'center',
    alignItems: 'center',
  },
  retroHeaderButtonShare: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#0080ff',
    borderWidth: 3,
    borderColor: '#231f20',
    justifyContent: 'center',
    alignItems: 'center',
  },
  retroTitleContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 12,
  },
  retroPathText: {
    fontFamily: FunkyFonts.marker,
    fontSize: 20,
    color: '#231f20',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  retroMiddleFrame: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 16,
    paddingHorizontal: 20,
  },
  retroPosterWrapper: {
    width: '100%',
    aspectRatio: 3 / 4,
    position: 'relative',
    borderWidth: 3,
    borderColor: '#231f20',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    padding: 6,
    shadowColor: '#ff3562',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
  },
  retroPosterImg: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  retroBottomConsole: {
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 10,
    gap: 12,
  },
  retroDateContainer: {
    width: '100%',
    paddingVertical: 12,
    borderWidth: 3,
    borderColor: '#231f20',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#231f20',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
  },
  retroDateText: {
    color: '#ff3562',
    fontSize: 16,
    fontFamily: FunkyFonts.marker,
    letterSpacing: 0.5,
  },
  retroArcadeInfoBox: {
    borderWidth: 3,
    borderColor: '#231f20',
    borderRadius: 18,
    padding: 4,
    shadowColor: '#ff3562',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
    backgroundColor: '#ffde4a',
  },
  retroArcadeInfoInner: {
    borderWidth: 3,
    borderColor: '#231f20',
    borderRadius: 14,
    paddingVertical: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    backgroundColor: '#ffffff',
  },
  retroArcadeInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    width: '100%',
  },
  retroArcadeInfoBadge: {
    backgroundColor: '#ff3562',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 3,
    borderColor: '#231f20',
    borderRadius: 10,
    transform: [{ rotate: '-2deg' }],
  },
  retroArcadeInfoBadgeText: {
    color: '#ffffff',
    fontFamily: FunkyFonts.marker,
    fontSize: 13,
    letterSpacing: 0.5,
  },
  retroArcadeInfoStripe: {
    flex: 1,
    height: 6,
    backgroundColor: '#231f20',
    marginLeft: 10,
    borderRadius: 3,
  },
  retroArcadeVisitorDescription: {
    fontFamily: FunkyFonts.marker,
    fontSize: 15,
    lineHeight: 24,
    color: '#231f20',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  retroArcadeGalleryHeader: {
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  retroArcadeGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  retroArcadeGalleryKickerBadge: {
    backgroundColor: '#0080ff',
    color: '#ffffff',
    fontFamily: FunkyFonts.marker,
    fontSize: 11,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 2,
    borderColor: '#231f20',
    borderRadius: 6,
    textTransform: 'uppercase',
  },
  retroArcadeGalleryKickerText: {
    fontFamily: FunkyFonts.marker,
    fontSize: 12,
    color: '#231f20',
    marginLeft: 8,
    textTransform: 'uppercase',
  },
  retroArcadeGalleryKickerBolt: {
    width: 14,
    height: 14,
    backgroundColor: '#ff3562',
    marginLeft: 6,
    borderRadius: 7,
  },
  retroArcadeGalleryTitle: {
    fontFamily: FunkyFonts.marker,
    fontSize: 28,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  retroArcadePhotoTile: {
    backgroundColor: '#ffffff',
    borderWidth: 3,
    borderColor: '#231f20',
    borderRadius: 18,
    padding: 4,
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 4,
    overflow: 'hidden',
  },
  retroArcadePhotoTileAlt: {
    transform: [{ rotate: '1.5deg' }],
  },
  retroArcadeGalleryImg: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  popHeroCanvas: {
    width: '100%',
    height: 465,
    backgroundColor: '#ffe84a',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    paddingTop: 16,
  },
  popTitleContainerOuter: {
    position: 'absolute',
    top: 20,
    zIndex: 10,
    transform: [{ rotate: '-1.5deg' }],
  },
  popTitleContainerShadow: {
    position: 'absolute',
    top: 4, left: 4, right: -4, bottom: -4,
    backgroundColor: '#ef2b3a',
    borderRadius: 18,
    borderWidth: 3,
    borderColor: '#231f20',
  },
  popTitleContainer: {
    backgroundColor: '#fffdf3',
    borderWidth: 3,
    borderColor: '#231f20',
    paddingHorizontal: 22,
    paddingVertical: 8,
    borderRadius: 18,
  },
  popTitleText: {
    fontFamily: FunkyFonts.marker,
    fontSize: 24,
    color: '#0080ff',
    textTransform: 'uppercase',
    letterSpacing: -0.5,
  },
  popPolaroidFrame: {
    marginTop: 82,
    width: 340,
    height: 310,
    backgroundColor: '#ffffff',
    borderWidth: 4,
    borderColor: '#231f20',
    padding: 12,
    paddingBottom: 24,
    borderRadius: 16,
    transform: [{ rotate: '2.5deg' }],
    shadowColor: '#231f20',
    shadowOffset: { width: 8, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    position: 'relative',
  },
  popPolaroidInner: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: '#231f20',
    overflow: 'hidden',
    backgroundColor: '#f5f5f5',
  },
  popPolaroidImage: {
    width: '100%',
    height: '100%',
  },
  popPolaroidOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: '#ffe84a',
    opacity: 0.05,
  },
  popPolaroidCaption: {
    fontFamily: FunkyFonts.marker,
    fontSize: 13,
    color: '#231f20',
    textAlign: 'center',
    textTransform: 'uppercase',
    flex: 1,
  },
  popPolaroidCaptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 12,
    paddingHorizontal: 4,
  },
  popCaptionBackBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#0080ff',
    borderWidth: 2.5,
    borderColor: '#231f20',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#231f20',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  popCaptionShareBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#ff4fb8',
    borderWidth: 2.5,
    borderColor: '#231f20',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#231f20',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 2,
  },
  popSticker: {
    position: 'absolute',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 2.5,
    borderColor: '#231f20',
    zIndex: 20,
  },
  popStickerLeft: {
    top: -12,
    left: -20,
    backgroundColor: '#0080ff',
    transform: [{ rotate: '-12deg' }],
  },
  popStickerRight: {
    top: 110,
    right: -24,
    backgroundColor: '#ff4fb8',
    transform: [{ rotate: '8deg' }],
  },
  popStickerText: {
    fontFamily: FunkyFonts.marker,
    fontSize: 12,
    color: '#ffffff',
    textTransform: 'uppercase',
  },
  popBubbleTailOuter: {
    position: 'absolute',
    bottom: -13,
    left: '50%',
    marginLeft: -12,
    width: 24,
    height: 24,
    overflow: 'hidden',
    zIndex: 4,
  },
  popBubbleTail: {
    width: 14,
    height: 14,
    backgroundColor: '#fffdf3',
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderColor: '#231f20',
    transform: [{ rotate: '45deg' }],
    marginTop: -8,
    marginLeft: 5,
  },
  popBackgroundShapeBlue: {
    position: 'absolute',
    top: 60,
    left: -40,
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 3,
    borderColor: '#231f20',
    backgroundColor: '#0080ff',
    opacity: 0.12,
    transform: [{ rotate: '-12deg' }],
  },
  popBackgroundShapePink: {
    position: 'absolute',
    bottom: 50,
    right: -45,
    width: 120,
    height: 120,
    borderWidth: 3,
    borderColor: '#231f20',
    backgroundColor: '#ff4fb8',
    opacity: 0.12,
    transform: [{ rotate: '45deg' }],
  },
  popStickerCapContainer: {
    position: 'absolute',
    top: -24,
    right: -24,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#ffe84a',
    borderWidth: 3,
    borderColor: '#231f20',
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ rotate: '15deg' }],
    zIndex: 25,
    shadowColor: '#231f20',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
  },
  popStickerCapEmoji: {
    fontSize: 26,
  },
  scrapbookTape: {
    position: 'absolute',
    width: 70,
    height: 22,
    borderRadius: 6,
    backgroundColor: 'rgba(246, 213, 143, 0.74)',
    borderWidth: 1,
    borderColor: 'rgba(217, 130, 107, 0.18)',
    zIndex: 3,
  },
  scrapbookTapeLeft: {
    top: -10,
    left: 22,
    transform: [{ rotate: '-8deg' }],
  },
  scrapbookTapeRight: {
    top: -8,
    right: 26,
    transform: [{ rotate: '7deg' }],
  },
  scrapbookSticker: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(217, 130, 107, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(217, 130, 107, 0.18)',
    marginBottom: 10,
  },
  scrapbookStickerText: {
    color: '#72493f',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  titleRowMain: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  renameHeroBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(212, 175, 55, 0.1)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(212, 175, 55, 0.3)' },
  heroMeta: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8 },
  heroDate: { fontSize: 14, color: MidnightColors.gold, fontFamily: Fonts.inter.bold, textTransform: 'uppercase', letterSpacing: 1 },
  editDateBtn: { paddingHorizontal: 4, paddingVertical: 2 },
  editCoverBtn: { position: 'absolute', top: 80, right: 20, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: 'rgba(0,0,0,0.5)', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  editCoverText: { color: '#fff', fontSize: 12, fontFamily: Fonts.inter.bold },
};
