import { StyleSheet } from 'react-native';
import { Fonts } from '../../constants/theme';

export const sportsStyles = {
  sportsHeroStage: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 28,
    overflow: 'hidden',
  },
  sportsHeroImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  sportsHeroOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  sportsTextureLayer: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.56,
  },
  sportsTextureLine: {
    position: 'absolute',
    height: 1,
    left: 22,
    right: 22,
  },
  sportsTextureLineTop: {
    top: 116,
  },
  sportsTextureLineMid: {
    top: 246,
    left: 72,
  },
  sportsTextureLineBottom: {
    bottom: 174,
    right: 80,
  },
  sportsAccentOrb: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    right: -72,
    top: 110,
    opacity: 0.28,
  },
  sportsTopBar: {
    position: 'absolute',
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 5,
  },
  sportsHeaderButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 4,
  },
  sportsTopLabel: {
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2.2,
  },
  sportsPosterFrame: {
    position: 'absolute',
    top: 116,
    right: 20,
    width: 184,
    height: 224,
    borderRadius: 26,
    padding: 8,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.24,
    shadowRadius: 28,
    elevation: 7,
  },
  sportsPosterImage: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
  },
  sportsPosterShade: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 26,
  },
  sportsPosterBadge: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 14,
    borderWidth: 1,
  },
  sportsPosterBadgeText: {
    fontSize: 8.5,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  sportsMetricCard: {
    position: 'absolute',
    left: 22,
    top: 232,
    width: 92,
    height: 104,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 5,
  },
  sportsMetricNumber: {
    fontSize: 30,
    lineHeight: 32,
    fontFamily: Fonts.spaceGrotesk.bold,
  },
  sportsMetricLabel: {
    fontSize: 9,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  sportsHeroCard: {
    width: '94%',
    alignSelf: 'flex-start',
    paddingHorizontal: 22,
    paddingVertical: 23,
    borderRadius: 28,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 30,
    elevation: 6,
  },
  sportsHeroKickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  sportsHeroKickerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  sportsHeroKicker: {
    fontSize: 10.5,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  sportsHeroKickerLine: {
    flex: 1,
    height: 1,
  },
  sportsHeroTitle: {
    fontSize: 39,
    lineHeight: 40,
    letterSpacing: 0,
  },
  sportsHeroDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 18,
  },
  sportsHeroDividerLine: {
    flex: 1,
    height: 1,
  },
  sportsHeroDividerMark: {
    width: 30,
    height: 5,
    borderRadius: 999,
  },
  sportsHeroMetaRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sportsHeroDate: {
    flex: 1,
    fontSize: 12,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  sportsShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 999,
  },
  sportsShareButtonText: {
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  sportsVisitorHeaderContainer: {
    height: 68,
    marginTop: -8,
    marginBottom: 8,
    borderBottomWidth: 1,
  },
  sportsVisitorHeaderContent: {
    paddingHorizontal: 18,
    alignItems: 'center',
    gap: 10,
  },
  sportsVisitorTab: {
    minHeight: 38,
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: 15,
    borderWidth: 1,
  },
  sportsVisitorTabText: {
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.25,
  },
  sportsInfoBox: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 30,
    padding: 0,
    borderRadius: 26,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 28,
    elevation: 4,
  },
  sportsInfoInner: {
    paddingHorizontal: 22,
    paddingVertical: 23,
  },
  sportsInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  sportsInfoMark: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  sportsInfoKicker: {
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.9,
  },
  sportsInfoLine: {
    flex: 1,
    height: 1,
  },
  sportsVisitorDescription: {
    fontSize: 15,
    lineHeight: 24.5,
    fontFamily: Fonts.inter.regular,
    textAlign: 'left',
  },
  sportsGalleryHeader: {
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 18,
  },
  sportsGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 9,
  },
  sportsGalleryKickerText: {
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.8,
  },
  sportsGalleryKickerLine: {
    width: 54,
    height: 1,
  },
  sportsGalleryTitle: {
    fontSize: 34,
    lineHeight: 36,
  },
  sportsPhotoCount: {
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginTop: 4,
  },
  sportsPhotoTile: {
    borderWidth: 1,
    borderRadius: 22,
    padding: 7,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 3,
  },
  sportsPhotoTileFeatured: {
    shadowOpacity: 0.18,
  },
  sportsPhotoLabel: {
    position: 'absolute',
    left: 13,
    top: 13,
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
  },
  sportsPhotoLabelNumber: {
    fontSize: 11,
    fontFamily: Fonts.spaceGrotesk.bold,
  },
  sportsPhotoLabelText: {
    fontSize: 8,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  sportsGalleryImg: {
    borderRadius: 16,
  },
};
