import { StyleSheet } from 'react-native';
import { Fonts } from '../../constants/theme';

export const techSleekStyles = {
  techSleekHeroStage: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    paddingHorizontal: 20,
    paddingBottom: 26,
    overflow: 'hidden',
    backgroundColor: '#050b17',
  },
  techSleekBackdrop: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.42,
  },
  techSleekHeroGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  techSleekGrid: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.5,
  },
  techSleekGridLine: {
    position: 'absolute',
    backgroundColor: 'rgba(125, 211, 252, 0.12)',
  },
  techSleekGridVerticalOne: {
    top: 80,
    bottom: 80,
    left: 36,
    width: 1,
  },
  techSleekGridVerticalTwo: {
    top: 132,
    bottom: 120,
    right: 86,
    width: 1,
  },
  techSleekGridHorizontalOne: {
    left: 20,
    right: 24,
    top: 152,
    height: 1,
  },
  techSleekGridHorizontalTwo: {
    left: 74,
    right: 18,
    bottom: 182,
    height: 1,
  },
  techSleekGlowOrb: {
    position: 'absolute',
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: 'rgba(14, 165, 233, 0.22)',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 44,
  },
  techSleekGlowTop: {
    top: 72,
    right: -88,
  },
  techSleekGlowBottom: {
    bottom: 112,
    left: -104,
    backgroundColor: 'rgba(37, 99, 235, 0.18)',
  },
  techSleekTopBar: {
    position: 'absolute',
    left: 20,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 5,
  },
  techSleekHeaderButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(8, 15, 30, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.28)',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 4,
  },
  techSleekHeaderLabel: {
    color: '#dbeafe',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2.4,
  },
  techSleekDeviceFrame: {
    position: 'absolute',
    top: 118,
    right: 18,
    width: 194,
    height: 236,
    borderRadius: 32,
    padding: 8,
    backgroundColor: 'rgba(241, 245, 249, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.24)',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.22,
    shadowRadius: 30,
    elevation: 7,
  },
  techSleekDeviceImage: {
    width: '100%',
    height: '100%',
    borderRadius: 25,
  },
  techSleekDeviceGlass: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 32,
  },
  techSleekDeviceBadge: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 16,
    backgroundColor: 'rgba(3, 7, 18, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.22)',
  },
  techSleekDeviceBadgeText: {
    color: '#7dd3fc',
    fontSize: 9,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  techSleekMetricCard: {
    position: 'absolute',
    top: 236,
    left: 22,
    width: 92,
    height: 104,
    borderRadius: 24,
    backgroundColor: 'rgba(8, 15, 30, 0.74)',
    borderWidth: 1,
    borderColor: 'rgba(34, 211, 238, 0.24)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 5,
  },
  techSleekMetricNumber: {
    color: '#f8fafc',
    fontSize: 30,
    lineHeight: 32,
    fontFamily: Fonts.spaceGrotesk.bold,
  },
  techSleekMetricLabel: {
    color: '#7dd3fc',
    fontSize: 9,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  techSleekHeroCard: {
    width: '94%',
    alignSelf: 'flex-start',
    paddingHorizontal: 22,
    paddingVertical: 23,
    borderRadius: 30,
    backgroundColor: 'rgba(8, 15, 30, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.22)',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 34,
    elevation: 6,
  },
  techSleekKickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  techSleekKickerDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#22d3ee',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 8,
  },
  techSleekKicker: {
    color: '#7dd3fc',
    fontSize: 10.5,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  techSleekKickerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(125, 211, 252, 0.24)',
  },
  techSleekHeroTitle: {
    color: '#f8fafc',
    fontSize: 40,
    lineHeight: 41,
    fontFamily: Fonts.spaceGrotesk.bold,
    letterSpacing: 0,
  },
  techSleekDivider: {
    height: 1,
    backgroundColor: 'rgba(125, 211, 252, 0.2)',
    marginTop: 18,
  },
  techSleekMetaRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  techSleekDate: {
    flex: 1,
    color: '#cbd5e1',
    fontSize: 12,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  techSleekShare: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#22d3ee',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 4,
  },
  techSleekShareText: {
    color: '#03101f',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  techSleekVisitorHeaderContainer: {
    height: 70,
    marginTop: -8,
    marginBottom: 8,
    backgroundColor: '#050b17',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(125, 211, 252, 0.12)',
  },
  techSleekVisitorHeaderContent: {
    paddingHorizontal: 18,
    alignItems: 'center',
    gap: 10,
  },
  techSleekVisitorTab: {
    minHeight: 38,
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.74)',
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.18)',
  },
  techSleekVisitorTabActive: {
    backgroundColor: '#22d3ee',
    borderColor: '#22d3ee',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 4,
  },
  techSleekVisitorTabText: {
    color: '#cbd5e1',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.25,
  },
  techSleekVisitorTabTextActive: {
    color: '#03101f',
  },
  techSleekInfoBox: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 30,
    padding: 0,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.18)',
    backgroundColor: 'rgba(8, 15, 30, 0.84)',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.14,
    shadowRadius: 30,
    elevation: 4,
  },
  techSleekInfoInner: {
    paddingHorizontal: 22,
    paddingVertical: 23,
  },
  techSleekInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  techSleekInfoPulse: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#22d3ee',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 8,
  },
  techSleekInfoKicker: {
    color: '#7dd3fc',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.9,
  },
  techSleekInfoLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(125, 211, 252, 0.2)',
  },
  techSleekVisitorDescription: {
    color: '#dbeafe',
    fontSize: 15,
    lineHeight: 24,
    fontFamily: Fonts.inter.regular,
    textAlign: 'left',
  },
  techSleekGalleryHeader: {
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 18,
  },
  techSleekGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 9,
  },
  techSleekGalleryKickerText: {
    color: '#22d3ee',
    fontSize: 10,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.8,
  },
  techSleekGalleryKickerLine: {
    width: 54,
    height: 1,
    backgroundColor: 'rgba(125, 211, 252, 0.28)',
  },
  techSleekGalleryTitle: {
    color: '#f8fafc',
    fontSize: 34,
    lineHeight: 36,
    fontFamily: Fonts.spaceGrotesk.bold,
  },
  techSleekPhotoCount: {
    color: '#7dd3fc',
    fontSize: 11,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginTop: 4,
  },
  techSleekPhotoTile: {
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.18)',
    borderRadius: 22,
    padding: 6,
    backgroundColor: 'rgba(8, 15, 30, 0.86)',
    shadowColor: '#22d3ee',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 3,
  },
  techSleekPhotoTileFeatured: {
    borderColor: 'rgba(34, 211, 238, 0.44)',
    shadowOpacity: 0.24,
  },
  techSleekPhotoLabel: {
    position: 'absolute',
    left: 12,
    top: 12,
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: 'rgba(3, 7, 18, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.22)',
  },
  techSleekPhotoLabelNumber: {
    color: '#f8fafc',
    fontSize: 11,
    fontFamily: Fonts.spaceGrotesk.bold,
  },
  techSleekPhotoLabelText: {
    color: '#7dd3fc',
    fontSize: 8,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  techSleekGalleryImg: {
    borderRadius: 17,
  },
};
