import { StyleSheet, Dimensions, Platform } from 'react-native';
import { MidnightColors, Fonts } from '../../constants/theme';
import { FunkyFonts } from './funkyFonts';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const visitorImmersiveStyles = {
// Visitor Immersive Styles
  visitorHeaderContainer: {
    width: '100%',
    height: 60,
    zIndex: 100,
    marginTop: 8,
    marginBottom: 0,
  },
  visitorHeaderContent: {
    paddingHorizontal: 20,
    alignItems: 'center',
    gap: 10,
  },
  scrapbookVisitorHeaderContainer: {
    height: 72,
    marginTop: 12,
  },
  scrapbookVisitorHeaderContent: {
    paddingHorizontal: 18,
    gap: 12,
  },
  neonVisitorHeaderContainer: {
    height: 72,
    marginTop: 10,
  },
  neonVisitorHeaderContent: {
    paddingHorizontal: 18,
    gap: 12,
  },
  pastelVisitorHeaderContainer: {
    height: 72,
    marginTop: 10,
  },
  pastelVisitorHeaderContent: {
    paddingHorizontal: 18,
    gap: 12,
  },
  popVisitorHeaderContainer: {
    height: 74,
    marginTop: 10,
  },
  popVisitorHeaderContent: {
    paddingHorizontal: 18,
    gap: 12,
  },
  cyberVisitorHeaderContainer: {
    height: 72,
    marginTop: 10,
    backgroundColor: '#05070c',
    borderBottomWidth: 1,
    borderColor: 'rgba(0, 240, 255, 0.1)',
  },
  cyberVisitorHeaderContent: {
    paddingHorizontal: 18,
    gap: 12,
  },
  retroArcadeVisitorHeaderContainer: {
    height: 74,
    marginTop: 10,
    backgroundColor: '#ffde4a',
    borderBottomWidth: 3,
    borderColor: '#231f20',
  },

  neonCarnivalVisitorHeaderContainer: {
    height: 72,
    marginTop: 10,
    backgroundColor: '#0c0714',
    borderBottomWidth: 1,
    borderColor: 'rgba(217, 70, 239, 0.2)',
  },
  neonCarnivalVisitorHeaderContent: {
    paddingHorizontal: 18,
    gap: 12,
  },
  neonCarnivalVisitorTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: 'rgba(12, 7, 20, 0.9)',
    borderWidth: 2,
    borderColor: 'rgba(217, 70, 239, 0.15)',
  },
  neonCarnivalVisitorTabActive: {
    backgroundColor: 'rgba(217, 70, 239, 0.08)',
    borderColor: '#d946ef',
    shadowColor: '#d946ef',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 4,
  },
  neonCarnivalVisitorTabText: {
    fontFamily: 'TiltNeon_400Regular',
    fontSize: 13,
    color: 'rgba(216, 180, 254, 0.7)',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  neonCarnivalVisitorTabTextActive: {
    color: '#d946ef',
    textShadowColor: 'rgba(217, 70, 239, 0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  retroArcadeVisitorHeaderContent: {
    paddingHorizontal: 18,
    gap: 12,
  },
  goldenVisitorHeaderContainer: {
    height: 68,
    marginTop: 12,
    marginBottom: 4,
  },
  goldenVisitorHeaderContent: {
    paddingHorizontal: 20,
    gap: 14,
  },
  vintageVisitorHeaderContainer: {
    height: 70,
    marginTop: 14,
    marginBottom: 8,
  },
  vintageVisitorHeaderContent: {
    paddingHorizontal: 20,
    gap: 14,
  },
  roseVisitorHeaderContainer: {
    height: 70,
    marginTop: 12,
    marginBottom: 8,
  },
  roseVisitorHeaderContent: {
    paddingHorizontal: 20,
    gap: 13,
  },
  minimalVisitorHeaderContainer: {
    height: 68,
    marginTop: 12,
    marginBottom: 8,
  },
  minimalVisitorHeaderContent: {
    paddingHorizontal: 20,
    gap: 13,
  },
  visitorTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(2, 6, 23, 0.6)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  scrapbookVisitorTab: {
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 253, 249, 0.72)',
    borderColor: 'rgba(38, 51, 49, 0.1)',
    shadowColor: '#d9826b',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  visitorTabActive: {
    backgroundColor: MidnightColors.gold,
    borderColor: MidnightColors.gold,
  },
  scrapbookVisitorTabActive: {
    backgroundColor: '#f6d58f',
    borderColor: 'rgba(217, 130, 107, 0.28)',
    transform: [{ translateY: -2 }, { rotate: '-0.4deg' }],
  },
  neonVisitorTab: {
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: 'rgba(16, 14, 34, 0.72)',
    borderColor: 'rgba(102, 232, 255, 0.18)',
  },
  neonVisitorTabActive: {
    backgroundColor: 'rgba(255, 61, 242, 0.18)',
    borderColor: 'rgba(255, 61, 242, 0.72)',
    shadowColor: '#ff3df2',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 4,
    transform: [{ translateY: -2 }],
  },
  pastelVisitorTab: {
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 253, 251, 0.78)',
    borderColor: 'rgba(213, 180, 220, 0.22)',
    shadowColor: '#d8b4dc',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 2,
  },
  pastelVisitorTabActive: {
    backgroundColor: '#f8d9de',
    borderColor: 'rgba(201, 118, 139, 0.24)',
    transform: [{ translateY: -2 }],
  },
  popVisitorTab: {
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 18,
    backgroundColor: '#fffdf3',
    borderColor: '#231f20',
    borderWidth: 2,
    shadowColor: '#231f20',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  popVisitorTabActive: {
    backgroundColor: '#0080ff',
    borderColor: '#231f20',
    transform: [{ translateY: -2 }, { rotate: '-1deg' }],
  },
  cyberVisitorTab: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 4,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cyberVisitorTabActive: {
    backgroundColor: 'rgba(0, 240, 255, 0.08)',
  },
  retroArcadeVisitorTab: {
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderColor: '#231f20',
    borderWidth: 2,
    shadowColor: '#231f20',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 3,
  },
  retroArcadeVisitorTabActive: {
    backgroundColor: '#ff3562',
    borderColor: '#231f20',
    transform: [{ translateY: -2 }, { rotate: '-1.5deg' }],
  },
  goldenVisitorTab: {
    paddingHorizontal: 21,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 250, 240, 0.58)',
    borderWidth: 1,
    borderColor: 'rgba(201, 154, 46, 0.12)',
    shadowColor: '#c99a2e',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 1,
  },
  goldenVisitorTabActive: {
    backgroundColor: 'rgba(201, 154, 46, 0.18)',
    borderColor: 'rgba(201, 154, 46, 0.24)',
    transform: [{ translateY: -1 }],
  },
  vintageVisitorTab: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#15130F',
    borderWidth: 1,
    borderColor: 'rgba(184, 145, 69, 0.44)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 3,
  },
  vintageVisitorTabActive: {
    backgroundColor: '#B89145',
    borderColor: '#B89145',
    transform: [{ translateY: -1 }],
  },
  roseVisitorTab: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 252, 247, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.18)',
    shadowColor: '#b76578',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 2,
  },
  roseVisitorTabActive: {
    backgroundColor: 'rgba(183, 101, 120, 0.18)',
    borderColor: 'rgba(183, 101, 120, 0.34)',
    transform: [{ translateY: -1 }],
  },
  minimalVisitorTab: {
    paddingHorizontal: 20,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 250, 242, 0.82)',
    borderWidth: 1,
    borderColor: 'rgba(109, 75, 52, 0.12)',
    shadowColor: '#6d4b34',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  minimalVisitorTabActive: {
    backgroundColor: '#4a2f1d',
    borderColor: '#4a2f1d',
    transform: [{ translateY: -1 }],
  },
  visitorTabText: {
    color: MidnightColors.gold,
    fontSize: 14,
    fontFamily: Fonts.outfit.bold,
  },
  scrapbookVisitorTabText: {
    fontSize: 13,
    fontFamily: Fonts.outfit.bold,
    letterSpacing: 0.2,
  },
  neonVisitorTabText: {
    fontSize: 12,
    fontFamily: Fonts.outfit.extraBold,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  pastelVisitorTabText: {
    fontSize: 13,
    fontFamily: Fonts.outfit.bold,
    letterSpacing: 0.15,
  },
  popVisitorTabText: {
    fontSize: 13,
    fontFamily: FunkyFonts.marker,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  goldenVisitorTabText: {
    fontSize: 12.5,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 0.85,
  },
  visitorTabTextActive: {
    color: MidnightColors.background,
  },
  goldenVisitorTabTextActive: {
    color: '#3f2f22',
    fontFamily: Fonts.nunitoSans.bold,
  },
  vintageVisitorTabText: {
    fontSize: 12.5,
    fontFamily: Fonts.inter.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1.25,
    color: '#F2E7D2',
  },
  vintageVisitorTabTextActive: {
    color: '#211A12',
    fontFamily: Fonts.inter.bold,
  },
  roseVisitorTabText: {
    fontSize: 12.5,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 0.85,
    color: '#562733',
  },
  roseVisitorTabTextActive: {
    color: '#562733',
    fontFamily: Fonts.nunitoSans.bold,
  },
  minimalVisitorTabText: {
    fontSize: 12.5,
    fontFamily: Fonts.nunitoSans.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 0.9,
    color: '#4a2f1d',
  },
  minimalVisitorTabTextActive: {
    color: '#fffaf2',
    fontFamily: Fonts.nunitoSans.bold,
  },
  scrapbookVisitorTabTextActive: {
    color: '#263331',
  },
  neonVisitorTabTextActive: {
    color: '#66e8ff',
  },
  pastelVisitorTabTextActive: {
    color: '#7b555b',
  },
  popVisitorTabTextActive: {
    color: '#ffffff',
  },
  cyberVisitorTabText: {
    fontSize: 16,
    fontFamily: Fonts.vt323.regular,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: 'rgba(0, 240, 255, 0.5)',
  },
  cyberVisitorTabTextActive: {
    color: '#00f0ff',
    fontFamily: Fonts.vt323.regular,
    fontSize: 16,
    textTransform: 'uppercase',
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 240, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  retroArcadeVisitorTabText: {
    fontSize: 13,
    fontFamily: FunkyFonts.marker,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: '#231f20',
  },
  retroArcadeVisitorTabTextActive: {
    color: '#ffffff',
  },
  cyberInfoBox: {
    backgroundColor: '#05070c',
    borderColor: 'rgba(0, 240, 255, 0.15)',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  cyberInfoInner: {
    borderWidth: 1,
    borderColor: 'rgba(0, 240, 255, 0.08)',
    borderRadius: 6,
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cyberInfoHeader: {
    marginBottom: 12,
    alignItems: 'center',
  },
  cyberInfoKicker: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 16,
    color: '#00f0ff',
    letterSpacing: 1.5,
  },
  cyberVisitorDescription: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
    color: '#e2eafc',
    textTransform: 'uppercase',
  },
  cyberPartnersTitle: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 28,
    color: '#00f0ff',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  cyberPartnersSubtitle: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 16,
    color: 'rgba(0, 240, 255, 0.6)',
    textAlign: 'center',
    lineHeight: 20,
    maxWidth: '85%',
  },
  cyberEmptyText: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 18,
    color: 'rgba(0, 240, 255, 0.5)',
    textTransform: 'uppercase',
    marginTop: 12,
  },
  cyberPartnerCard: {
    backgroundColor: 'rgba(0, 240, 255, 0.02)',
    borderColor: 'rgba(0, 240, 255, 0.15)',
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    marginBottom: 4,
  },
  cyberPartnerName: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 20,
    color: '#e2eafc',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  cyberPartnerType: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 14,
    color: '#00f0ff',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cyberGalleryKicker: {
    marginBottom: 4,
  },
  cyberGalleryKickerText: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 14,
    color: 'rgba(0, 240, 255, 0.5)',
    letterSpacing: 1.5,
  },
  cyberGalleryTitle: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 26,
    color: '#e2eafc',
    textTransform: 'uppercase',
  },
  cyberPhotoCount: {
    fontFamily: Fonts.vt323.regular,
    fontSize: 16,
    color: '#00f0ff',
    marginTop: 2,
  },

  visitorContent: {
    paddingTop: 0,
  },
  mainInfoBox: {
    padding: 24,
    backgroundColor: 'rgba(255,255,255,0.02)',
    marginHorizontal: 12, // Reduced to make the card wider
    marginTop: 6,
    marginBottom: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
  },
  scrapbookInfoBox: {
    marginHorizontal: 18,
    marginTop: 14,
    marginBottom: 26,
    padding: 12,
    borderRadius: 26,
    borderWidth: 1,
    shadowColor: '#d9826b',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 3,
  },
  scrapbookInfoInner: {
    paddingHorizontal: 18,
    paddingVertical: 22,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(38, 51, 49, 0.08)',
    backgroundColor: 'rgba(255, 253, 249, 0.58)',
  },
  neonInfoBox: {
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 24,
    padding: 1,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(102, 232, 255, 0.26)',
    shadowColor: '#7e57ff',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.22,
    shadowRadius: 28,
    elevation: 6,
  },
  neonInfoInner: {
    paddingHorizontal: 18,
    paddingVertical: 20,
    borderRadius: 26,
    backgroundColor: 'rgba(12, 11, 27, 0.78)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  neonInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginBottom: 12,
  },
  neonInfoPulse: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ff3df2',
  },
  neonInfoKicker: {
    color: '#66e8ff',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.3,
  },
  neonInfoLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(102, 232, 255, 0.24)',
  },
  pastelInfoBox: {
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 24,
    padding: 10,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(213, 180, 220, 0.24)',
    backgroundColor: 'rgba(255, 253, 251, 0.62)',
    shadowColor: '#f4b8a8',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.13,
    shadowRadius: 24,
    elevation: 3,
  },
  pastelInfoInner: {
    paddingHorizontal: 18,
    paddingVertical: 22,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
    borderWidth: 1,
    borderColor: 'rgba(201, 118, 139, 0.12)',
  },
  pastelInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginBottom: 12,
  },
  pastelInfoPetal: {
    width: 10,
    height: 10,
    borderRadius: 6,
    backgroundColor: '#f4b8a8',
  },
  pastelInfoKicker: {
    color: '#9a8583',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  pastelInfoLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(201, 118, 139, 0.18)',
  },
  goldenInfoBox: {
    marginHorizontal: 18,
    marginTop: 18,
    marginBottom: 30,
    padding: 8,
    borderRadius: 26,
    borderWidth: 0,
    backgroundColor: 'rgba(255, 250, 240, 0.26)',
    shadowColor: '#c99a2e',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.08,
    shadowRadius: 28,
    elevation: 2,
  },
  goldenInfoInner: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderRadius: 22,
    borderWidth: 0,
    backgroundColor: 'rgba(255, 250, 240, 0.68)',
  },
  vintageInfoBox: {
    marginHorizontal: 18,
    marginTop: 20,
    marginBottom: 32,
    padding: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(184, 145, 69, 0.42)',
    backgroundColor: '#15130F',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.28,
    shadowRadius: 30,
    elevation: 4,
  },
  vintageInfoInner: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderRadius: 17,
    backgroundColor: '#1C1812',
  },
  roseInfoBox: {
    marginHorizontal: 16,
    marginTop: 18,
    marginBottom: 30,
    padding: 8,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.14)',
    backgroundColor: 'rgba(255, 249, 245, 0.42)',
    shadowColor: '#b76578',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.1,
    shadowRadius: 26,
    elevation: 3,
  },
  roseInfoInner: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(183, 101, 120, 0.13)',
    backgroundColor: 'rgba(255, 252, 247, 0.82)',
  },
  minimalInfoBox: {
    marginHorizontal: 18,
    marginTop: 18,
    marginBottom: 28,
    padding: 0,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(109, 75, 52, 0.1)',
    backgroundColor: '#fffaf2',
    shadowColor: '#6d4b34',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.1,
    shadowRadius: 26,
    elevation: 3,
  },
  minimalInfoInner: {
    paddingHorizontal: 22,
    paddingVertical: 24,
    borderRadius: 26,
    backgroundColor: 'rgba(255, 250, 242, 0.92)',
  },
  anniversaryInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginBottom: 12,
  },
  vintageInfoHeader: {
    gap: 10,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    borderBottomColor: 'rgba(184, 145, 69, 0.34)',
  },
  minimalInfoHeader: {
    marginBottom: 14,
  },
  anniversaryInfoMark: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  goldenInfoMark: {
    backgroundColor: '#c99a2e',
  },
  vintageInfoMark: {
    width: 22,
    height: 1,
    borderRadius: 0,
    backgroundColor: '#B89145',
  },
  roseInfoMark: {
    backgroundColor: '#8f9f7b',
  },
  minimalInfoMark: {
    width: 24,
    height: 1,
    borderRadius: 0,
    backgroundColor: '#6d4b34',
  },
  anniversaryInfoKicker: {
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.25,
  },
  goldenInfoKicker: {
    color: '#9a6f22',
    fontSize: 10.5,
    fontFamily: Fonts.nunitoSans.semiBold,
    letterSpacing: 1.8,
  },
  vintageInfoKicker: {
    color: '#C7A96B',
    fontFamily: Fonts.inter.semiBold,
    letterSpacing: 2,
  },
  roseInfoKicker: {
    color: '#9a6c74',
    fontFamily: Fonts.nunitoSans.semiBold,
    letterSpacing: 1.7,
  },
  minimalInfoKicker: {
    color: '#8a7461',
    fontFamily: Fonts.nunitoSans.semiBold,
    letterSpacing: 1.8,
  },
  anniversaryInfoLine: {
    flex: 1,
    height: 1,
  },
  goldenInfoLine: {
    backgroundColor: 'rgba(201, 154, 46, 0.28)',
  },
  vintageInfoLine: {
    backgroundColor: 'rgba(184, 145, 69, 0.28)',
  },
  roseInfoLine: {
    backgroundColor: 'rgba(183, 101, 120, 0.22)',
  },
  minimalInfoLine: {
    backgroundColor: 'rgba(109, 75, 52, 0.14)',
  },
  popInfoBox: {
    marginHorizontal: 10,
    marginTop: 16,
    marginBottom: 26,
    padding: 0,
    borderRadius: 24,
    borderWidth: 3,
    borderColor: '#231f20',
    backgroundColor: '#fffdf3',
    shadowColor: '#ef2b3a',
    shadowOffset: { width: 7, height: 7 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
  },
  popInfoInner: {
    paddingHorizontal: 18,
    paddingVertical: 20,
    borderRadius: 20,
    backgroundColor: '#fffdf3',
    borderWidth: 0,
  },
  popInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  popInfoBang: {
    width: 28,
    height: 28,
    borderRadius: 14,
    overflow: 'hidden',
    textAlign: 'center',
    lineHeight: 28,
    backgroundColor: '#0080ff',
    borderWidth: 2.5,
    borderColor: '#231f20',
    color: '#ffffff',
    fontFamily: FunkyFonts.marker,
    fontSize: 18,
  },
  popInfoKicker: {
    color: '#231f20',
    fontSize: 13,
    fontFamily: FunkyFonts.marker,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  popInfoStripe: {
    flex: 1,
    height: 4,
    backgroundColor: '#ff4fb8',
    borderWidth: 1,
    borderColor: '#231f20',
  },
  scrapbookInfoRule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  scrapbookInfoRuleBottom: {
    marginTop: 16,
    marginBottom: 0,
  },
  scrapbookInfoRuleLine: {
    flex: 1,
    height: 1,
    opacity: 0.65,
  },
  scrapbookInfoRuleShort: {
    width: 42,
    height: 1,
    backgroundColor: 'rgba(38, 51, 49, 0.16)',
  },
  visitorDescription: {
    fontSize: 15,
    color: MidnightColors.slate400,
    fontFamily: Fonts.inter.regular,
    lineHeight: 22,
  },
  neonVisitorDescription: {
    color: '#e7e3ff',
    lineHeight: 23,
  },
  pastelVisitorDescription: {
    color: '#5d5350',
    lineHeight: 24,
  },
  popVisitorDescription: {
    color: '#231f20',
    fontFamily: FunkyFonts.marker,
    fontSize: 18,
    lineHeight: 26,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  goldenVisitorDescription: {
    color: '#4d3928',
    fontFamily: Fonts.nunitoSans.regular,
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.05,
  },
  vintageVisitorDescription: {
    color: '#EFE3C7',
    fontFamily: Fonts.inter.regular,
    lineHeight: 25,
    letterSpacing: 0.05,
  },
  roseVisitorDescription: {
    color: '#562733',
    fontFamily: Fonts.nunitoSans.regular,
    fontSize: 15,
    lineHeight: 25,
  },
  minimalVisitorDescription: {
    color: '#5b3e29',
    fontFamily: Fonts.nunitoSans.regular,
    fontSize: 15,
    lineHeight: 25,
  },
  categoryBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(212, 175, 55, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginTop: 12,
  },
  categoryBadgeText: {
    color: MidnightColors.gold,
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
  },

  galleryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: 24,
    marginBottom: 16,
    marginTop: 10,
  },
  scrapbookGalleryHeader: {
    marginTop: 18,
    marginBottom: 22,
    paddingHorizontal: 22,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(38, 51, 49, 0.1)',
  },
  neonGalleryHeader: {
    marginTop: 18,
    marginBottom: 20,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(102, 232, 255, 0.16)',
  },
  pastelGalleryHeader: {
    marginTop: 18,
    marginBottom: 22,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(201, 118, 139, 0.12)',
  },
  goldenGalleryHeader: {
    marginTop: 24,
    marginBottom: 28,
    paddingHorizontal: 22,
    paddingBottom: 18,
    borderBottomWidth: 0,
  },
  vintageGalleryHeader: {
    marginTop: 28,
    marginBottom: 28,
    paddingHorizontal: 22,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(184, 145, 69, 0.24)',
  },
  roseGalleryHeader: {
    marginTop: 24,
    marginBottom: 28,
    paddingHorizontal: 22,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(183, 101, 120, 0.16)',
  },
  minimalGalleryHeader: {
    marginTop: 24,
    marginBottom: 28,
    paddingHorizontal: 22,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(109, 75, 52, 0.12)',
  },
  popGalleryHeader: {
    marginTop: 24,
    marginBottom: 16,
    marginHorizontal: 16,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
  },
  scrapbookGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  scrapbookGalleryKickerLine: {
    width: 34,
    height: 2,
    borderRadius: 1,
  },
  scrapbookGalleryKickerText: {
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  neonGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 7,
  },
  neonGallerySpark: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ff3df2',
  },
  neonGalleryKickerText: {
    color: '#66e8ff',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  neonGalleryKickerLine: {
    width: 44,
    height: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 61, 242, 0.72)',
  },
  pastelGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 7,
  },
  pastelGalleryKickerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#d8b4dc',
  },
  pastelGalleryKickerText: {
    color: '#9a8583',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.35,
  },
  pastelGalleryKickerLine: {
    width: 42,
    height: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(244, 184, 168, 0.72)',
  },
  popGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  popGalleryKickerBadge: {
    color: '#ffffff',
    backgroundColor: '#ef2b3a',
    borderWidth: 2,
    borderColor: '#231f20',
    borderRadius: 9,
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 2,
    fontSize: 10,
    fontFamily: Fonts.outfit.extraBold,
    letterSpacing: 0,
  },
  popGalleryKickerText: {
    color: '#231f20',
    fontSize: 10,
    fontFamily: FunkyFonts.marker,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  popGalleryKickerBolt: {
    width: 36,
    height: 4,
    backgroundColor: '#ffe84a',
    borderWidth: 1,
    borderColor: '#231f20',
    transform: [{ rotate: '-4deg' }],
  },
  anniversaryGalleryKicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  vintageGalleryKicker: {
    gap: 11,
  },
  minimalGalleryKicker: {
    gap: 10,
  },
  anniversaryGalleryDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  goldenGalleryDot: {
    backgroundColor: 'rgba(201, 154, 46, 0.78)',
  },
  vintageGalleryDot: {
    borderRadius: 0,
    width: 22,
    height: 1,
    backgroundColor: '#B89145',
  },
  roseGalleryDot: {
    backgroundColor: '#8f9f7b',
  },
  minimalGalleryDot: {
    width: 24,
    height: 1,
    borderRadius: 0,
    backgroundColor: '#6d4b34',
  },
  anniversaryGalleryKickerText: {
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.35,
  },
  goldenGalleryKickerText: {
    color: '#9a6f22',
    fontSize: 10.5,
    fontFamily: Fonts.nunitoSans.semiBold,
    letterSpacing: 1.85,
  },
  vintageGalleryKickerText: {
    color: '#C7A96B',
    fontFamily: Fonts.inter.semiBold,
    letterSpacing: 2,
  },
  roseGalleryKickerText: {
    color: '#9a6c74',
    fontFamily: Fonts.nunitoSans.semiBold,
    letterSpacing: 1.65,
  },
  minimalGalleryKickerText: {
    color: '#8a7461',
    fontFamily: Fonts.nunitoSans.semiBold,
    letterSpacing: 1.8,
  },
  anniversaryGalleryLine: {
    width: 42,
    height: 2,
    borderRadius: 999,
  },
  goldenGalleryLine: {
    backgroundColor: 'rgba(201, 154, 46, 0.36)',
  },
  vintageGalleryLine: {
    height: 1,
    backgroundColor: 'rgba(184, 145, 69, 0.34)',
  },
  roseGalleryLine: {
    backgroundColor: 'rgba(183, 101, 120, 0.42)',
  },
  minimalGalleryLine: {
    height: 1,
    backgroundColor: 'rgba(109, 75, 52, 0.18)',
  },
  galleryTitle: {
    fontSize: 24,
    color: '#fff',
    fontFamily: Fonts.outfit.bold,
  },
  scrapbookGalleryTitle: {
    fontSize: 28,
    letterSpacing: 0,
  },
  neonGalleryTitle: {
    fontSize: 28,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  pastelGalleryTitle: {
    fontSize: 29,
    letterSpacing: 0,
  },
  popGalleryTitle: {
    color: '#231f20',
    fontSize: 32,
    fontFamily: FunkyFonts.marker,
    textTransform: 'uppercase',
    letterSpacing: -0.5,
  },
  goldenGalleryTitle: {
    fontSize: 34,
    lineHeight: 39,
    fontFamily: Fonts.cormorant.semiBold,
    letterSpacing: 0,
  },
  vintageGalleryTitle: {
    color: '#F2E7D2',
    fontSize: 34,
    lineHeight: 38,
    fontFamily: Fonts.cormorant.bold,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  roseGalleryTitle: {
    color: '#562733',
    fontSize: 32,
    lineHeight: 37,
    fontFamily: Fonts.cormorant.bold,
    letterSpacing: 0,
  },
  minimalGalleryTitle: {
    color: '#3b2618',
    fontSize: 34,
    lineHeight: 38,
    fontFamily: Fonts.cormorant.bold,
    letterSpacing: 0,
  },
  photoCount: {
    fontSize: 12,
    color: MidnightColors.gold,
    fontFamily: Fonts.inter.medium,
    opacity: 0.7,
  },
  photoLoading: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoGrid: {
    flexDirection: 'column',
    width: '100%',
    alignSelf: 'stretch',
    paddingBottom: 40,
    paddingHorizontal: 12,
  },
  masonryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 12,
  },
  masonryColumn: {
    flex: 1,
    flexDirection: 'column',
    gap: 12,
  },
  photoCard: {
    width: '100%',
  },
  photoTile: {
    flex: 1,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  scrapbookPhotoTile: {
    padding: 9,
    borderWidth: 1,
    borderRadius: 22,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 2,
    transform: [{ rotate: '-0.35deg' }],
  },
  scrapbookPhotoTileAlt: {
    transform: [{ rotate: '0.35deg' }],
  },
  neonPhotoTile: {
    borderWidth: 1,
    borderRadius: 24,
    overflow: 'hidden',
    padding: 3,
    backgroundColor: 'rgba(14, 12, 31, 0.9)',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.24,
    shadowRadius: 22,
    elevation: 5,
  },
  neonPhotoTileFeatured: {
    borderWidth: 1.5,
    shadowOpacity: 0.34,
    transform: [{ scale: 0.995 }],
  },
  neonPhotoGlowLine: {
    position: 'absolute',
    left: 16,
    right: 16,
    height: 2,
    borderRadius: 999,
    zIndex: 2,
  },
  neonPhotoGlowLineTop: {
    top: 12,
  },
  neonPhotoGlowLineBottom: {
    bottom: 12,
  },
  pastelPhotoTile: {
    padding: 9,
    borderWidth: 1,
    borderRadius: 26,
    overflow: 'hidden',
    backgroundColor: '#fffdfb',
    shadowOffset: { width: 0, height: 13 },
    shadowOpacity: 0.13,
    shadowRadius: 20,
    elevation: 3,
    transform: [{ rotate: '-0.2deg' }],
  },
  pastelPhotoTileAlt: {
    transform: [{ rotate: '0.25deg' }],
  },
  pastelPhotoTape: {
    position: 'absolute',
    width: 58,
    height: 18,
    borderRadius: 6,
    backgroundColor: 'rgba(216, 180, 220, 0.48)',
    borderWidth: 1,
    borderColor: 'rgba(201, 118, 139, 0.12)',
    zIndex: 2,
  },
  pastelPhotoTapeLeft: {
    top: 12,
    left: 18,
    transform: [{ rotate: '-7deg' }],
  },
  pastelPhotoTapeRight: {
    right: 18,
    bottom: 12,
    transform: [{ rotate: '6deg' }],
    backgroundColor: 'rgba(189, 223, 217, 0.52)',
  },
  pastelPhotoDot: {
    position: 'absolute',
    width: 7,
    height: 7,
    borderRadius: 4,
    zIndex: 2,
  },
  pastelPhotoDotTop: {
    top: 42,
    right: 24,
    backgroundColor: '#f4b8a8',
  },
  pastelPhotoDotBottom: {
    left: 24,
    bottom: 42,
    backgroundColor: '#d8b4dc',
  },
  goldenPhotoTile: {
    padding: 8,
    borderWidth: 0,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 250, 240, 0.88)',
    shadowColor: '#8a6421',
    shadowOffset: { width: 0, height: 13 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 2,
  },
  goldenPhotoTileAlt: {
    transform: [{ rotate: '0.18deg' }],
  },
  anniversaryPhotoAccent: {
    position: 'absolute',
    left: 18,
    right: 18,
    height: 2,
    borderRadius: 999,
    zIndex: 2,
  },
  goldenPhotoAccentTop: {
    top: 13,
    backgroundColor: 'rgba(201, 154, 46, 0.28)',
  },
  goldenPhotoAccentBottom: {
    bottom: 13,
    backgroundColor: 'rgba(201, 154, 46, 0.16)',
  },
  vintagePhotoTile: {
    padding: 8,
    borderWidth: 1,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#D6C29A',
    borderColor: 'rgba(184, 145, 69, 0.44)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.26,
    shadowRadius: 24,
    elevation: 4,
  },
  vintagePhotoTileAlt: {
    transform: [{ rotate: '-0.16deg' }],
  },
  vintagePhotoFrameLine: {
    position: 'absolute',
    left: 14,
    right: 14,
    height: 1,
    backgroundColor: 'rgba(33, 26, 18, 0.22)',
    zIndex: 2,
  },
  vintagePhotoFrameLineTop: {
    top: 14,
  },
  vintagePhotoFrameLineBottom: {
    bottom: 14,
  },
  rosePhotoTile: {
    padding: 8,
    borderWidth: 1,
    borderRadius: 26,
    overflow: 'hidden',
    backgroundColor: '#fffdfa',
    borderColor: 'rgba(183, 101, 120, 0.14)',
    shadowColor: '#b76578',
    shadowOffset: { width: 0, height: 13 },
    shadowOpacity: 0.1,
    shadowRadius: 22,
    elevation: 3,
  },
  rosePhotoTileAlt: {
    transform: [{ rotate: '0.2deg' }],
  },
  rosePhotoPetal: {
    position: 'absolute',
    width: 34,
    height: 34,
    borderRadius: 18,
    backgroundColor: 'rgba(183, 101, 120, 0.14)',
    zIndex: 2,
  },
  rosePhotoPetalTop: {
    top: 14,
    right: 16,
  },
  rosePhotoPetalBottom: {
    left: 16,
    bottom: 14,
    backgroundColor: 'rgba(143, 159, 123, 0.16)',
  },
  minimalPhotoTile: {
    padding: 8,
    paddingBottom: 20,
    borderWidth: 1,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: '#fffaf2',
    borderColor: 'rgba(109, 75, 52, 0.1)',
    shadowColor: '#6d4b34',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 22,
    elevation: 3,
  },
  minimalPhotoTileAlt: {
    opacity: 0.98,
    transform: [{ rotate: '-0.35deg' }],
  },
  minimalPhotoIndex: {
    position: 'absolute',
    top: 10,
    left: 10,
    zIndex: 2,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(74, 47, 29, 0.88)',
  },
  minimalPhotoIndexText: {
    color: '#fffaf2',
    fontSize: 10,
    fontFamily: Fonts.nunitoSans.bold,
  },
  popPhotoTile: {
    padding: 8,
    borderWidth: 3,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: '#fffdf3',
    shadowOffset: { width: 7, height: 7 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
    transform: [{ rotate: '-0.45deg' }],
  },
  popPhotoTileAlt: {
    transform: [{ rotate: '0.45deg' }],
  },
  popPhotoCorner: {
    position: 'absolute',
    width: 36,
    height: 36,
    zIndex: 3,
    borderWidth: 3,
    borderColor: '#231f20',
    backgroundColor: '#ffe84a',
  },
  popPhotoCornerTopLeft: {
    top: 12,
    left: 12,
    borderBottomRightRadius: 18,
  },
  popPhotoCornerBottomRight: {
    right: 12,
    bottom: 12,
    borderTopLeftRadius: 18,
    backgroundColor: '#ff4fb8',
  },
  popPhotoHalftone: {
    position: 'absolute',
    zIndex: 2,
    width: 54,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#231f20',
    backgroundColor: '#0080ff',
    opacity: 0.88,
  },
  popPhotoHalftoneTop: {
    top: 18,
    right: 22,
    transform: [{ rotate: '8deg' }],
  },
  popPhotoHalftoneBottom: {
    left: 22,
    bottom: 18,
    backgroundColor: '#ef2b3a',
    transform: [{ rotate: '-8deg' }],
  },
  scrapbookCorner: {
    position: 'absolute',
    width: 22,
    height: 22,
    opacity: 0.75,
    zIndex: 2,
  },
  scrapbookCornerTopLeft: {
    top: 14,
    left: 14,
    borderTopWidth: 2,
    borderLeftWidth: 2,
  },
  scrapbookCornerBottomRight: {
    right: 14,
    bottom: 14,
    borderRightWidth: 2,
    borderBottomWidth: 2,
  },
  galleryImg: {
    width: '100%',
    height: '100%',
  },
  scrapbookGalleryImg: {
    borderRadius: 14,
  },
  neonGalleryImg: {
    borderRadius: 20,
  },
  pastelGalleryImg: {
    borderRadius: 18,
  },
  popGalleryImg: {
    borderRadius: 14,
  },
  goldenGalleryImg: {
    borderRadius: 16,
  },
  vintageGalleryImg: {
    borderRadius: 10,
    opacity: 0.88,
  },
  roseGalleryImg: {
    borderRadius: 19,
    opacity: 0.94,
  },
  minimalGalleryImg: {
    borderRadius: 16,
  },
  emptyGallery: {
    width: '100%',
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  viewerContainer: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  fullImage: {
    width: '100%',
    height: '80%',
  },
  fullImageWithComments: {
    height: '46%',
    marginBottom: SCREEN_WIDTH * 0.86,
  },
  viewerClose: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 10,
    padding: 10,
  },
  navBtnLeft: {
    position: 'absolute',
    left: 20,
    top: '50%',
    marginTop: -25,
    zIndex: 10,
    padding: 15,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 30,
  },
  navBtnRight: {
    position: 'absolute',
    right: 20,
    top: '50%',
    marginTop: -25,
    zIndex: 10,
    padding: 15,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 30,
  },
  viewerFooter: {
    position: 'absolute',
    bottom: 40,
    paddingHorizontal: 20,
  },
  viewerText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: Fonts.inter.bold,
  },
  viewerActions: {
    position: 'absolute',
    flexDirection: 'row',
    gap: 44,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 12,
  },
  viewerActionsDocked: {
    bottom: 72,
  },
  viewerActionsRaised: {
    bottom: SCREEN_WIDTH * 0.9,
  },
  viewerAction: {
    alignItems: 'center',
    gap: 4,
  },
  viewerActionCount: {
    color: '#ffffff',
    fontSize: 11,
    fontFamily: Fonts.inter.bold,
  },
  neonViewerActionCount: {
    color: '#66e8ff',
  },
  popViewerActionCount: {
    color: '#ffe84a',
    fontFamily: FunkyFonts.marker,
    fontSize: 14,
  },
  guestbookPanel: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
    height: SCREEN_WIDTH * 0.86,
    backgroundColor: '#fafaf9',
    borderRadius: 28,
    overflow: 'hidden',
    zIndex: 11,
  },
  guestbookHeader: {
    paddingHorizontal: 24,
    paddingTop: 22,
    paddingBottom: 18,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e7e5e4',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  guestbookTitle: {
    color: '#0f172a',
    fontSize: 24,
    fontFamily: Fonts.outfit.bold,
    fontStyle: 'italic',
  },
  guestbookSubtitle: {
    color: '#57534e',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginTop: 5,
  },
  closeGuestbookBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#f5f5f4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guestbookList: {
    flex: 1,
  },
  guestbookListContent: {
    padding: 22,
    paddingBottom: 26,
  },
  emptyGuestbook: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 44,
    opacity: 0.55,
  },
  emptyGuestbookIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#f5f5f4',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyGuestbookTitle: {
    color: '#0f172a',
    fontSize: 18,
    fontFamily: Fonts.outfit.bold,
    fontStyle: 'italic',
  },
  emptyGuestbookText: {
    color: '#57534e',
    fontSize: 13,
    fontFamily: Fonts.inter.regular,
    marginTop: 6,
  },
  commentThread: {
    marginBottom: 22,
  },
  commentItem: {
    flexDirection: 'row',
    gap: 12,
  },
  commentAvatar: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: '#1e293b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentAvatarText: {
    color: '#ffffff',
    fontSize: 13,
    fontFamily: Fonts.inter.bold,
  },
  commentContent: {
    flex: 1,
    minWidth: 0,
  },
  commentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  commentName: {
    flex: 1,
    color: '#0f172a',
    fontSize: 12,
    fontFamily: Fonts.inter.bold,
    paddingRight: 8,
  },
  commentTime: {
    color: '#78716c',
    fontSize: 10,
    fontFamily: Fonts.inter.medium,
  },
  commentBubble: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#f5f5f4',
    borderRadius: 18,
    borderTopLeftRadius: 2,
    padding: 14,
  },
  commentText: {
    color: '#57534e',
    fontSize: 13,
    fontFamily: Fonts.inter.regular,
    lineHeight: 19,
  },
  commentActions: {
    flexDirection: 'row',
    gap: 18,
    marginTop: 10,
  },
  replyBtnText: {
    color: MidnightColors.gold,
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    letterSpacing: 1.5,
  },
  deleteBtnText: {
    color: '#fb7185',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    letterSpacing: 1.5,
  },
  replyItem: {
    flexDirection: 'row',
    gap: 10,
    marginLeft: 50,
    marginTop: 14,
  },
  replyAvatar: {
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
  },
  replyAvatarText: {
    color: '#ffffff',
    fontSize: 11,
    fontFamily: Fonts.inter.bold,
  },
  replyName: {
    flex: 1,
    color: '#1e293b',
    fontSize: 11,
    fontFamily: Fonts.inter.bold,
    paddingRight: 8,
  },
  replyBubble: {
    backgroundColor: '#f5f5f4',
    borderWidth: 1,
    borderColor: '#e7e5e4',
    borderRadius: 14,
    borderTopLeftRadius: 2,
    padding: 11,
  },
  replyText: {
    color: '#44403c',
    fontSize: 12,
    fontFamily: Fonts.inter.regular,
    fontStyle: 'italic',
    lineHeight: 18,
  },
  replyDeleteText: {
    marginTop: 6,
    fontSize: 9,
  },
  commentComposer: {
    padding: 16,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#f5f5f4',
  },
  replyingToBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#fafaf9',
    borderWidth: 1,
    borderColor: '#f5f5f4',
    marginBottom: 10,
  },
  replyingToText: {
    color: '#57534e',
    fontSize: 10,
    fontFamily: Fonts.inter.bold,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  replyingToName: {
    color: MidnightColors.gold,
  },
  commentInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  commentInput: {
    flex: 1,
    minHeight: 48,
    borderRadius: 22,
    backgroundColor: '#fafaf9',
    borderWidth: 1,
    borderColor: '#f5f5f4',
    paddingHorizontal: 18,
    color: '#0f172a',
    fontSize: 14,
    fontFamily: Fonts.inter.regular,
  },
  commentSendBtn: {
    width: 46,
    height: 46,
    borderRadius: 15,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentSendBtnDisabled: {
    opacity: 0.25,
  },
  deleteMainBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 16, backgroundColor: 'rgba(239, 68, 68, 0.1)', borderRadius: 12, marginTop: 32, marginBottom: 20, borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.2)' },
  deleteMainText: { color: '#ef4444', fontSize: 14, fontFamily: Fonts.inter.bold },

  etherealDividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginVertical: 24,
    alignSelf: 'center',
    width: '60%',
  },
  etherealDividerLine: {
    flex: 1,
    height: 1,
    opacity: 0.25,
  },
  etherealDividerAsterisk: {
    fontSize: 14,
    opacity: 0.8,
  },

  royalDividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginVertical: 24,
    alignSelf: 'center',
    width: '60%',
  },
  royalDividerLine: {
    flex: 1,
    height: 1,
    opacity: 0.3,
  },
  royalDividerDiamond: {
    fontSize: 10,
    transform: [{ scaleY: 1.2 }],
    opacity: 0.75,
  },
};
